-- AiCensus catalog expansion: coding agents, AI browsers, model benchmarks,
-- AI infrastructure, creative video/image tools, and knowledge-work tools.

BEGIN;

WITH new_tools AS (
  SELECT *
  FROM jsonb_to_recordset($tools$
[
  {
    "slug": "claude-code",
    "name": "Claude Code",
    "tagline": "Anthropic's agentic coding tool for terminal, IDE, GitHub, and cloud software tasks.",
    "description": "Claude Code is Anthropic's coding agent for reading repositories, editing files, running commands, reviewing changes, and helping developers move from issue to pull request. It works from the terminal and related Anthropic surfaces, making it useful for multi-file changes, bug fixing, refactors, and codebase exploration.",
    "website_url": "https://www.anthropic.com/product/claude-code",
    "category_slug": "coding-development",
    "pricing_model": "paid",
    "pricing_details": "Available through Anthropic plans and API usage; higher limits depend on Pro, Max, team, enterprise, or usage-based access.",
    "editor_rating": 4.7,
    "company_name": "Anthropic",
    "founded_year": 2025,
    "key_features": ["Terminal-based coding agent", "Repository-aware file edits", "Runs commands and tests", "GitHub and cloud task workflows", "Claude model integration"],
    "pros": ["Excellent for multi-file software tasks", "Fits naturally into developer workflows"],
    "cons": ["Usage limits can matter on heavy agent work", "Requires careful review before merging output"],
    "use_cases": ["Bug fixing", "Refactoring", "Repository exploration", "Test generation", "Pull request preparation"],
    "who_its_for": ["Software engineers", "Engineering teams", "AI-native startups"]
  },
  {
    "slug": "openai-codex",
    "name": "OpenAI Codex",
    "tagline": "OpenAI's coding agent for implementing tasks, reviewing changes, and shipping pull requests.",
    "description": "OpenAI Codex is an AI coding agent designed to complete software engineering tasks end to end, including reading code, making changes, running checks, and helping teams prepare pull requests. It is aimed at developers who want agentic help with implementation, migrations, refactors, and maintenance.",
    "website_url": "https://openai.com/codex/",
    "category_slug": "coding-development",
    "pricing_model": "freemium",
    "pricing_details": "Access and limits depend on ChatGPT plan or API/developer usage; pricing can vary by plan and model.",
    "editor_rating": 4.6,
    "company_name": "OpenAI",
    "founded_year": 2025,
    "key_features": ["Agentic coding tasks", "Pull request workflows", "Repository understanding", "Code review support", "OpenAI model integration"],
    "pros": ["Strong fit for implementation and maintenance tasks", "Ties into OpenAI's broader developer ecosystem"],
    "cons": ["Plan limits and model access vary", "Complex architecture still needs senior review"],
    "use_cases": ["Feature implementation", "Code review", "Bug fixing", "Migrations", "Developer automation"],
    "who_its_for": ["Developers", "Engineering teams", "Technical founders"]
  },
  {
    "slug": "gemini-cli",
    "name": "Gemini CLI",
    "tagline": "Google's open-source command-line AI agent for coding, research, and terminal workflows.",
    "description": "Gemini CLI is Google's open-source command-line interface for working with Gemini from the terminal. It helps developers ask questions, edit code, inspect projects, use tools, and automate parts of software and research workflows without leaving the shell.",
    "website_url": "https://google-gemini.github.io/gemini-cli/",
    "category_slug": "coding-development",
    "pricing_model": "open_source",
    "pricing_details": "Open-source CLI; model usage depends on Google account, API, or plan limits.",
    "editor_rating": 4.2,
    "company_name": "Google",
    "founded_year": 2025,
    "key_features": ["Open-source terminal CLI", "Gemini model access", "Tool and project workflows", "Developer automation", "Local command-line interface"],
    "pros": ["Free and open-source entry point", "Good fit for Gemini users in terminal workflows"],
    "cons": ["Model access and limits depend on Google setup", "You still need to review generated commands and edits"],
    "use_cases": ["Terminal AI assistance", "Codebase Q&A", "Small code edits", "Research from the shell", "Developer scripting"],
    "who_its_for": ["Developers", "Students", "Open-source builders"]
  },
  {
    "slug": "augment-code",
    "name": "Augment Code",
    "tagline": "AI coding platform built around deep codebase context and autonomous agent workflows.",
    "description": "Augment Code is an AI coding platform that indexes and understands large codebases, then uses that context for chat, code edits, completions, code review, and autonomous coding agents. It is strongest for teams working in established repositories where context quality matters.",
    "website_url": "https://www.augmentcode.com",
    "category_slug": "coding-development",
    "pricing_model": "freemium",
    "pricing_details": "Free or community-style access may be limited; paid individual, team, and enterprise plans add more agent and review capacity.",
    "editor_rating": 4.4,
    "company_name": "Augment",
    "founded_year": 2022,
    "key_features": ["Codebase context engine", "Autonomous coding agent", "IDE integrations", "AI code review", "Repository-scale search"],
    "pros": ["Strong on large repositories", "Context engine reduces repeated explanation"],
    "cons": ["Most valuable on larger codebases", "Pricing and credits can be harder to compare than flat plans"],
    "use_cases": ["Large-codebase development", "Code review", "Refactors", "Onboarding", "Enterprise engineering workflows"],
    "who_its_for": ["Engineering teams", "Enterprise developers", "Large-repo maintainers"]
  },
  {
    "slug": "granola",
    "name": "Granola",
    "tagline": "Bot-free AI meeting notes that turn your own notes and audio into structured follow-ups.",
    "description": "Granola is an AI meeting notes app that runs quietly in the background instead of joining meetings as a visible bot. It enhances your typed notes with meeting context, summaries, decisions, and follow-ups, making it useful for private, low-friction meeting capture.",
    "website_url": "https://www.granola.ai",
    "category_slug": "productivity",
    "pricing_model": "freemium",
    "pricing_details": "Free or trial access is available; paid individual and team plans unlock more meetings, history, and collaboration features.",
    "editor_rating": 4.4,
    "company_name": "Granola",
    "founded_year": 2023,
    "key_features": ["Bot-free meeting capture", "AI-enhanced notes", "Templates and structured summaries", "Spaces and folders", "Follow-up extraction"],
    "pros": ["Less awkward than meeting bots", "Works well with human-guided notes"],
    "cons": ["Best on supported desktop environments", "Not a full CRM or project management system"],
    "use_cases": ["Meeting notes", "Sales calls", "Product interviews", "Team follow-ups", "Executive summaries"],
    "who_its_for": ["Founders", "Product managers", "Sales teams", "Knowledge workers"]
  },
  {
    "slug": "glean",
    "name": "Glean",
    "tagline": "Enterprise AI search, assistant, and agent platform over company knowledge.",
    "description": "Glean is a workplace AI platform for enterprise search, AI assistants, agents, and knowledge discovery across company apps and documents. It respects permissions and builds a company knowledge graph so teams can find answers, sources, people, and workflows faster.",
    "website_url": "https://www.glean.com",
    "category_slug": "productivity",
    "pricing_model": "enterprise",
    "pricing_details": "Enterprise pricing is custom and depends on seats, connectors, data, deployment, and support needs.",
    "editor_rating": 4.5,
    "company_name": "Glean",
    "founded_year": 2019,
    "key_features": ["Enterprise search", "Permission-aware knowledge graph", "AI assistant", "Agents over company data", "SaaS connectors"],
    "pros": ["Strong fit for large company knowledge retrieval", "Designed around enterprise permissions"],
    "cons": ["Overkill for small teams", "Requires connector setup and internal data hygiene"],
    "use_cases": ["Enterprise search", "Internal knowledge assistant", "Employee onboarding", "Support enablement", "Company data agents"],
    "who_its_for": ["Enterprises", "IT teams", "Knowledge-heavy organizations"]
  },
  {
    "slug": "hugging-face",
    "name": "Hugging Face",
    "tagline": "The central hub for AI models, datasets, Spaces, libraries, and open-source ML collaboration.",
    "description": "Hugging Face is a major AI platform and community for hosting models, datasets, demos, Spaces, and machine learning libraries. It is the default place many developers go to discover open models, publish checkpoints, run demos, and build with Transformers, Diffusers, Datasets, and related tools.",
    "website_url": "https://huggingface.co",
    "category_slug": "models-infrastructure",
    "pricing_model": "freemium",
    "pricing_details": "Free public hosting and community features are available; paid Pro, team, enterprise, Inference Endpoints, and compute features add private and scalable capacity.",
    "editor_rating": 4.8,
    "company_name": "Hugging Face",
    "founded_year": 2016,
    "key_features": ["Model Hub", "Datasets Hub", "Spaces demos", "Transformers and Diffusers", "Inference and enterprise features"],
    "pros": ["Largest open AI ecosystem hub", "Excellent discovery and community signal"],
    "cons": ["Quality varies across community models", "Production deployment often needs extra infrastructure planning"],
    "use_cases": ["Model discovery", "Dataset hosting", "Open-source ML", "Demo hosting", "Inference endpoints"],
    "who_its_for": ["AI developers", "Researchers", "Startups", "Enterprise ML teams"]
  },
  {
    "slug": "replicate",
    "name": "Replicate",
    "tagline": "Run open and community AI models from a web playground or API.",
    "description": "Replicate is a platform for running machine learning models through a hosted web playground and API. It is popular with developers who want quick access to image, video, audio, and language models without provisioning their own GPU infrastructure.",
    "website_url": "https://replicate.com",
    "category_slug": "models-infrastructure",
    "pricing_model": "paid",
    "pricing_details": "Usage-based pricing varies by model, hardware, and runtime; some models may offer limited trial or public experimentation.",
    "editor_rating": 4.4,
    "company_name": "Replicate",
    "founded_year": 2019,
    "key_features": ["Hosted model API", "Web playground", "Community model catalog", "Image/video/audio models", "Deployment via Cog"],
    "pros": ["Fast way to test models by API", "Broad creative model catalog"],
    "cons": ["Costs can vary by model runtime", "Not every community model is production-stable"],
    "use_cases": ["Model prototyping", "Generative media APIs", "ML demos", "App integrations", "Batch generation"],
    "who_its_for": ["Developers", "AI app builders", "Creative technologists"]
  },
  {
    "slug": "fal-ai",
    "name": "fal.ai",
    "tagline": "Fast generative media APIs for images, video, audio, and creative model workflows.",
    "description": "fal.ai is an inference platform focused on high-speed generative media APIs, including image, video, audio, and creative model workflows. It is used by teams building products that need low-latency access to popular generative models without operating the GPU stack themselves.",
    "website_url": "https://fal.ai",
    "category_slug": "models-infrastructure",
    "pricing_model": "paid",
    "pricing_details": "Usage-based pricing varies by model, runtime, and generation type.",
    "editor_rating": 4.4,
    "company_name": "fal.ai",
    "founded_year": 2021,
    "key_features": ["Generative media APIs", "Fast image and video inference", "Model catalog", "Developer SDKs", "Production-oriented latency"],
    "pros": ["Strong fit for image and video products", "Developer-friendly API surface"],
    "cons": ["Usage costs can ramp with media-heavy products", "Model availability and rates vary"],
    "use_cases": ["Image generation APIs", "Video generation APIs", "Creative automation", "AI media apps", "Workflow orchestration"],
    "who_its_for": ["Developers", "Creative AI startups", "Media product teams"]
  },
  {
    "slug": "modal",
    "name": "Modal",
    "tagline": "Serverless AI infrastructure for running code, jobs, containers, and GPUs from Python.",
    "description": "Modal is an AI infrastructure platform for running serverless functions, jobs, containers, web endpoints, and GPU workloads from Python. It is useful for teams that want to train, fine-tune, batch process, or serve models without manually managing cloud infrastructure.",
    "website_url": "https://modal.com",
    "category_slug": "models-infrastructure",
    "pricing_model": "freemium",
    "pricing_details": "Free credits may be available; production usage is billed by compute, GPU, storage, and runtime.",
    "editor_rating": 4.5,
    "company_name": "Modal",
    "founded_year": 2021,
    "key_features": ["Serverless Python functions", "GPU workloads", "Containerized jobs", "Web endpoints", "Scheduled and batch workloads"],
    "pros": ["Excellent developer experience for GPU jobs", "No heavy cloud setup for many workloads"],
    "cons": ["Requires engineering comfort with Python/cloud patterns", "Not a no-code AI app platform"],
    "use_cases": ["Model serving", "Batch inference", "Fine-tuning", "Data jobs", "AI backend infrastructure"],
    "who_its_for": ["AI engineers", "Startups", "Backend developers", "ML teams"]
  },
  {
    "slug": "baseten",
    "name": "Baseten",
    "tagline": "Production AI inference platform for deploying, optimizing, and scaling models.",
    "description": "Baseten is an AI infrastructure platform for deploying and serving machine learning models in production. It supports model APIs, optimized inference, observability, scaling, and enterprise deployment patterns for teams that need reliable model serving.",
    "website_url": "https://www.baseten.co",
    "category_slug": "models-infrastructure",
    "pricing_model": "enterprise",
    "pricing_details": "Pricing depends on inference usage, deployment model, compute, enterprise controls, and support requirements.",
    "editor_rating": 4.5,
    "company_name": "Baseten",
    "founded_year": 2019,
    "key_features": ["Production model deployment", "Optimized inference", "OpenAI-compatible model APIs", "Observability", "Enterprise deployment options"],
    "pros": ["Built for production inference reliability", "Strong option for scaling AI products"],
    "cons": ["More infrastructure-focused than beginner-friendly", "Best value appears at production scale"],
    "use_cases": ["Production inference", "Model APIs", "Enterprise AI deployment", "Optimized serving", "AI product infrastructure"],
    "who_its_for": ["ML platform teams", "AI product companies", "Enterprises"]
  },
  {
    "slug": "chatgpt-atlas",
    "name": "ChatGPT Atlas",
    "tagline": "OpenAI's ChatGPT-native browser with AI assistance built into web browsing.",
    "description": "ChatGPT Atlas is OpenAI's AI browser built around ChatGPT. It brings ChatGPT into the browsing surface so users can ask about pages, use browser-aware assistance, manage data controls, and work with web context more directly.",
    "website_url": "https://help.openai.com/en/collections/16051538-chatgpt-atlas",
    "category_slug": "productivity",
    "pricing_model": "freemium",
    "pricing_details": "Availability and features depend on ChatGPT plan, platform, workspace, and rollout status.",
    "editor_rating": 4.2,
    "company_name": "OpenAI",
    "founded_year": 2025,
    "key_features": ["ChatGPT browser sidebar", "Page-aware assistance", "Browser data controls", "Workspace support", "Chromium-based browsing"],
    "pros": ["Tight ChatGPT integration while browsing", "Useful for research and reading workflows"],
    "cons": ["Platform availability and enterprise controls vary", "AI browsers require careful privacy settings"],
    "use_cases": ["Web research", "Reading assistance", "Page summarization", "Browser-based productivity", "AI browsing workflows"],
    "who_its_for": ["ChatGPT users", "Researchers", "Knowledge workers"]
  },
  {
    "slug": "perplexity-comet",
    "name": "Perplexity Comet",
    "tagline": "Perplexity's AI browser for search-first, page-aware browsing and assistant workflows.",
    "description": "Perplexity Comet is an AI browser that embeds Perplexity's answer engine and assistant into the browsing experience. It is designed for users who want search, summaries, tab-aware questions, and agentic browsing help without constantly switching apps.",
    "website_url": "https://www.perplexity.ai/comet",
    "category_slug": "research-search",
    "pricing_model": "freemium",
    "pricing_details": "Comet availability and feature limits vary by platform and Perplexity plan.",
    "editor_rating": 4.2,
    "company_name": "Perplexity",
    "founded_year": 2025,
    "key_features": ["AI browser", "Perplexity search integration", "Ask about open tabs", "Page summaries", "Agentic browsing assistance"],
    "pros": ["Strong search and citation DNA", "Good fit for research-heavy browsing"],
    "cons": ["AI browser privacy tradeoffs need attention", "Agentic browsing reliability varies by site"],
    "use_cases": ["Research browsing", "Tab summarization", "Shopping research", "Content discovery", "Answer-engine workflows"],
    "who_its_for": ["Researchers", "Students", "Perplexity users", "Knowledge workers"]
  },
  {
    "slug": "dia",
    "name": "Dia",
    "tagline": "AI-native browser from The Browser Company for chat, page context, and browsing workflows.",
    "description": "Dia is an AI browser from The Browser Company, the team behind Arc. It focuses on bringing AI chat and contextual assistance directly into browsing, with an emphasis on everyday web workflows rather than a separate chatbot tab.",
    "website_url": "https://www.diabrowser.com",
    "category_slug": "productivity",
    "pricing_model": "freemium",
    "pricing_details": "Availability, pricing, and platform support depend on The Browser Company's rollout and plan structure.",
    "editor_rating": 4.0,
    "company_name": "The Browser Company",
    "founded_year": 2025,
    "key_features": ["AI browser", "Contextual page assistance", "Chat while browsing", "Mac-first workflow", "Browser Company design"],
    "pros": ["Thoughtful browser UX heritage", "Useful for AI-assisted everyday browsing"],
    "cons": ["Still evolving compared with established browsers", "Platform support may be limited"],
    "use_cases": ["AI-assisted browsing", "Reading and writing on the web", "Research", "Productivity", "Web workflows"],
    "who_its_for": ["Power users", "Knowledge workers", "Arc users", "AI browser early adopters"]
  },
  {
    "slug": "arc-max",
    "name": "Arc Max",
    "tagline": "Opt-in AI features inside Arc Browser for summarizing, organizing, and browsing faster.",
    "description": "Arc Max is The Browser Company's set of AI features inside Arc Browser. It adds opt-in assistance for browser tasks like summarizing pages, improving tab organization, and making everyday browsing feel more intelligent.",
    "website_url": "https://arc.net/max",
    "category_slug": "productivity",
    "pricing_model": "freemium",
    "pricing_details": "Arc Max features are opt-in within Arc; availability and pricing depend on Arc's current product plan.",
    "editor_rating": 4.0,
    "company_name": "The Browser Company",
    "founded_year": 2023,
    "key_features": ["AI browser features", "Page summaries", "Tab and link assistance", "Arc integration", "Opt-in controls"],
    "pros": ["Fits directly into Arc's polished browser UX", "Useful lightweight AI for browsing tasks"],
    "cons": ["Not a full autonomous browser agent", "Best only if you already like Arc"],
    "use_cases": ["Page summaries", "Tab organization", "Link previews", "Everyday browsing", "Research shortcuts"],
    "who_its_for": ["Arc users", "Students", "Knowledge workers", "Browser power users"]
  },
  {
    "slug": "krea",
    "name": "Krea",
    "tagline": "AI creative suite for image generation, video generation, realtime creation, and visual workflows.",
    "description": "Krea is an AI creative platform for generating, enhancing, and animating images and videos. It brings together multiple image and video models with a workflow-oriented interface for designers, creators, marketers, and visual experimenters.",
    "website_url": "https://www.krea.ai",
    "category_slug": "image-generation",
    "pricing_model": "freemium",
    "pricing_details": "Free creation is limited; paid plans add more generations, higher quality, private workflows, and advanced creative features.",
    "editor_rating": 4.3,
    "company_name": "Krea",
    "founded_year": 2022,
    "key_features": ["Image generation", "Video generation", "Realtime creation", "Upscaling and enhancement", "Multi-model creative workflows"],
    "pros": ["Strong creative interface for visual iteration", "Useful across image and video workflows"],
    "cons": ["Model availability and quality can vary", "Heavy creative use can consume credits quickly"],
    "use_cases": ["Image generation", "Video animation", "Creative direction", "Marketing visuals", "Visual prototyping"],
    "who_its_for": ["Designers", "Creators", "Marketers", "Creative technologists"]
  },
  {
    "slug": "higgsfield",
    "name": "Higgsfield",
    "tagline": "Cinematic AI video and image platform with camera controls, storyboards, and creator workflows.",
    "description": "Higgsfield is an AI video and image generation platform focused on cinematic control, social content, professional camera movement, storyboarding, and creator workflows. It combines proprietary tools with partner models to help creators and marketers produce polished visual content.",
    "website_url": "https://higgsfield.ai",
    "category_slug": "video-audio",
    "pricing_model": "freemium",
    "pricing_details": "Free or starter access is limited; paid plans add more credits, advanced video controls, and professional workflows.",
    "editor_rating": 4.3,
    "company_name": "Higgsfield",
    "founded_year": 2023,
    "key_features": ["Cinematic video generation", "Camera and lens controls", "Storyboard workflows", "Image generation", "Creator and marketing tools"],
    "pros": ["Excellent fit for cinematic short-form workflows", "Strong creator and social video positioning"],
    "cons": ["Not a traditional video editor", "Credit usage can add up on iteration-heavy projects"],
    "use_cases": ["AI filmmaking", "Social video", "Product ads", "Storyboarding", "Cinematic visual campaigns"],
    "who_its_for": ["Creators", "Filmmakers", "Marketing teams", "Agencies"]
  },
  {
    "slug": "lmarena",
    "name": "LMArena",
    "tagline": "Community-powered model leaderboard for comparing AI systems through real user battles.",
    "description": "LMArena, now also branded as Arena, is a public evaluation platform for comparing AI models through blind, pairwise user judgments and leaderboards. It is one of the most-watched public signals for real-world model preference and chatbot performance.",
    "website_url": "https://arena.ai",
    "category_slug": "models-infrastructure",
    "pricing_model": "free",
    "pricing_details": "Free public leaderboard and arena access.",
    "editor_rating": 4.6,
    "company_name": "LMArena",
    "founded_year": 2023,
    "key_features": ["Blind pairwise battles", "Public model leaderboards", "Community voting", "Model comparison", "Research-backed evaluation"],
    "pros": ["Strong public signal for model preference", "Easy to understand model comparisons"],
    "cons": ["Preference rankings are not a full benchmark suite", "Arena results can shift as models and prompts change"],
    "use_cases": ["Model comparison", "Benchmark watching", "AI research", "Procurement research", "Model selection"],
    "who_its_for": ["AI builders", "Researchers", "Product teams", "Model evaluators"]
  },
  {
    "slug": "artificial-analysis",
    "name": "Artificial Analysis",
    "tagline": "Independent AI model benchmarks for intelligence, speed, pricing, context, and modalities.",
    "description": "Artificial Analysis tracks AI models across benchmark scores, speed, pricing, context windows, image inputs, speech, and other capability dimensions. It is useful for developers and buyers comparing model tradeoffs beyond marketing claims.",
    "website_url": "https://artificialanalysis.ai",
    "category_slug": "models-infrastructure",
    "pricing_model": "freemium",
    "pricing_details": "Public benchmark data is available; paid or API access may apply for deeper programmatic use.",
    "editor_rating": 4.5,
    "company_name": "Artificial Analysis",
    "founded_year": 2023,
    "key_features": ["Model benchmark dashboards", "Pricing comparisons", "Speed and latency data", "Context window tracking", "Multimodal benchmarks"],
    "pros": ["Practical model selection data", "Combines quality, speed, and cost dimensions"],
    "cons": ["Benchmarks cannot fully predict app-specific performance", "Fast-moving model market requires frequent checking"],
    "use_cases": ["Model selection", "Cost comparison", "AI procurement", "Benchmark research", "Developer planning"],
    "who_its_for": ["Developers", "AI product teams", "Analysts", "Procurement teams"]
  },
  {
    "slug": "swe-bench",
    "name": "SWE-bench",
    "tagline": "Software engineering benchmark and leaderboard for evaluating AI coding agents on real GitHub issues.",
    "description": "SWE-bench is a benchmark and leaderboard for evaluating language models and agents on real software engineering tasks drawn from GitHub repositories. SWE-bench Verified is widely used to compare coding-agent ability on human-filtered tasks.",
    "website_url": "https://www.swebench.com",
    "category_slug": "models-infrastructure",
    "pricing_model": "free",
    "pricing_details": "Free public benchmark, datasets, and leaderboard access.",
    "editor_rating": 4.6,
    "company_name": "SWE-bench",
    "founded_year": 2023,
    "key_features": ["Coding-agent benchmark", "Real GitHub issues", "Verified subset", "Leaderboards", "Agent comparison"],
    "pros": ["Important signal for coding-agent capability", "Uses realistic software tasks"],
    "cons": ["Leaderboard performance may not match every codebase", "Can be gamed or overfit like any benchmark"],
    "use_cases": ["Coding model evaluation", "Agent benchmarking", "AI research", "Tool selection", "Engineering procurement"],
    "who_its_for": ["AI researchers", "Engineering leaders", "Coding-agent builders", "Developers"]
  },
  {
    "slug": "stanford-helm",
    "name": "Stanford HELM",
    "tagline": "Open framework for holistic, reproducible evaluation of language and multimodal models.",
    "description": "Stanford HELM is an open-source evaluation framework from Stanford CRFM for holistic, reproducible, and transparent evaluation of foundation models. It helps researchers compare models across capabilities, scenarios, metrics, and risk dimensions.",
    "website_url": "https://github.com/stanford-crfm/helm",
    "category_slug": "models-infrastructure",
    "pricing_model": "open_source",
    "pricing_details": "Open-source framework and public research resources.",
    "editor_rating": 4.4,
    "company_name": "Stanford CRFM",
    "founded_year": 2022,
    "key_features": ["Open-source evaluation framework", "Holistic model metrics", "Reproducible runs", "Language and multimodal evaluation", "Research transparency"],
    "pros": ["Research-grade evaluation methodology", "Transparent and reproducible framework"],
    "cons": ["More technical than consumer leaderboards", "Requires setup and benchmark literacy"],
    "use_cases": ["Model evaluation", "Academic research", "Benchmarking", "Responsible AI analysis", "Foundation model comparison"],
    "who_its_for": ["Researchers", "ML engineers", "Policy teams", "AI evaluation teams"]
  }
]
$tools$::jsonb) AS t(
    slug text,
    name text,
    tagline text,
    description text,
    website_url text,
    category_slug text,
    pricing_model text,
    pricing_details text,
    editor_rating numeric,
    company_name text,
    founded_year integer,
    key_features jsonb,
    pros jsonb,
    cons jsonb,
    use_cases jsonb,
    who_its_for jsonb
  )
)
INSERT INTO public.tools (
  name,
  slug,
  tagline,
  description,
  website_url,
  category_id,
  pricing_model,
  pricing_details,
  editor_rating,
  is_verified,
  is_featured,
  status,
  published_at,
  company_name,
  founded_year,
  key_features,
  pros,
  cons,
  use_cases,
  who_its_for,
  meta_title,
  meta_description
)
SELECT
  t.name,
  t.slug,
  t.tagline,
  t.description,
  t.website_url,
  c.id,
  t.pricing_model::pricing_model,
  t.pricing_details,
  t.editor_rating,
  true,
  false,
  'published'::tool_status,
  now(),
  t.company_name,
  t.founded_year,
  ARRAY(SELECT jsonb_array_elements_text(COALESCE(t.key_features, '[]'::jsonb))),
  ARRAY(SELECT jsonb_array_elements_text(COALESCE(t.pros, '[]'::jsonb))),
  ARRAY(SELECT jsonb_array_elements_text(COALESCE(t.cons, '[]'::jsonb))),
  ARRAY(SELECT jsonb_array_elements_text(COALESCE(t.use_cases, '[]'::jsonb))),
  ARRAY(SELECT jsonb_array_elements_text(COALESCE(t.who_its_for, '[]'::jsonb))),
  t.name || ' Review, Pricing, Alternatives | AiCensus',
  left(t.description, 155)
FROM new_tools AS t
JOIN public.categories AS c ON c.slug = t.category_slug
ON CONFLICT (slug) DO UPDATE SET
  name = excluded.name,
  tagline = excluded.tagline,
  description = excluded.description,
  website_url = excluded.website_url,
  category_id = excluded.category_id,
  pricing_model = excluded.pricing_model,
  pricing_details = excluded.pricing_details,
  editor_rating = excluded.editor_rating,
  is_verified = excluded.is_verified,
  status = excluded.status,
  published_at = COALESCE(public.tools.published_at, excluded.published_at),
  company_name = excluded.company_name,
  founded_year = excluded.founded_year,
  key_features = excluded.key_features,
  pros = excluded.pros,
  cons = excluded.cons,
  use_cases = excluded.use_cases,
  who_its_for = excluded.who_its_for,
  meta_title = excluded.meta_title,
  meta_description = excluded.meta_description,
  updated_at = now();

COMMIT;
