-- AiCensus competitor gap fill: 15 tier-1/2 tools across coding, agents,
-- image, productivity, legal-adjacent, healthcare, and writing categories.

BEGIN;

WITH new_tools AS (
  SELECT *
  FROM jsonb_to_recordset($tools$
[
  {
    "slug": "codeium",
    "name": "Codeium",
    "tagline": "Free AI code completion and chat for 70+ languages across popular IDEs.",
    "description": "Codeium is an AI coding assistant offering autocomplete, in-editor chat, and codebase-aware search across VS Code, JetBrains, Vim, and other editors. Its long-running free tier makes it a popular alternative to paid copilots for individual developers and students.",
    "website_url": "https://codeium.com",
    "category_slug": "coding-development",
    "pricing_model": "freemium",
    "pricing_details": "Free tier for individuals with generous completion limits; Teams and Enterprise plans add admin controls, privacy options, and higher usage.",
    "editor_rating": 4.4,
    "company_name": "Exafunction",
    "founded_year": 2021,
    "key_features": ["Multi-IDE autocomplete", "In-editor chat", "Codebase search", "70+ language support", "Self-hosted enterprise options"],
    "pros": ["Strong free tier for individuals", "Works across many editors without switching IDEs"],
    "cons": ["Less agent depth than Cursor or Windsurf", "Enterprise features trail GitHub Copilot Business"],
    "use_cases": ["Daily code completion", "Quick refactors", "Learning new codebases", "Budget-conscious teams"],
    "who_its_for": ["Individual developers", "Students", "Teams wanting Copilot-like completions on a budget"]
  },
  {
    "slug": "dify",
    "name": "Dify",
    "tagline": "Open-source LLM app platform for building agents, RAG apps, and workflows.",
    "description": "Dify is an open-source platform for building production LLM applications with visual workflows, RAG pipelines, agent orchestration, and API deployment. It is widely used as a self-hostable alternative to proprietary agent builders and pairs well with multiple model providers.",
    "website_url": "https://dify.ai",
    "category_slug": "ai-agents",
    "pricing_model": "freemium",
    "pricing_details": "Free cloud sandbox; paid cloud tiers and self-hosted Community Edition available; Enterprise for advanced governance.",
    "editor_rating": 4.5,
    "company_name": "LangGenius",
    "founded_year": 2023,
    "key_features": ["Visual agent and workflow builder", "RAG and knowledge bases", "Multi-model support", "API and embed deployment", "Self-hosting option"],
    "pros": ["Fast path from prototype to deployed app", "Strong open-source community and templates"],
    "cons": ["Self-hosting requires ops effort", "Less polished than single-vendor SaaS for non-technical users"],
    "use_cases": ["Internal AI assistants", "Customer support bots", "RAG over company docs", "Agent prototyping"],
    "who_its_for": ["Developers", "AI product teams", "Startups building LLM features"]
  },
  {
    "slug": "photoroom",
    "name": "Photoroom",
    "tagline": "AI product photography and background removal for e-commerce and creators.",
    "description": "Photoroom helps sellers and marketers create clean product photos, remove backgrounds, generate scenes, and batch-edit catalog images with AI. It is optimized for e-commerce listings, social ads, and fast creative production without a studio.",
    "website_url": "https://www.photoroom.com",
    "category_slug": "image-generation",
    "pricing_model": "freemium",
    "pricing_details": "Free tier with limits; Pro and Business plans unlock batch editing, higher resolution, brand tools, and team features.",
    "editor_rating": 4.5,
    "company_name": "Photoroom",
    "founded_year": 2019,
    "key_features": ["Background removal", "AI product scenes", "Batch editing", "Templates for marketplaces", "Mobile and web apps"],
    "pros": ["Excellent for e-commerce and catalog workflows", "Fast results without Photoshop skills"],
    "cons": ["Less suited to fine art or complex compositing", "Advanced features require paid plans"],
    "use_cases": ["Product listings", "Marketplace photos", "Social ad creatives", "Catalog cleanup"],
    "who_its_for": ["E-commerce sellers", "Marketers", "Small brands", "Resellers"]
  },
  {
    "slug": "gong",
    "name": "Gong",
    "tagline": "Revenue intelligence platform that analyzes sales calls, deals, and coaching at scale.",
    "description": "Gong captures and analyzes customer conversations to surface deal risk, coaching opportunities, competitive mentions, and forecast insights. It goes beyond meeting notes into revenue intelligence for sales leaders and enablement teams.",
    "website_url": "https://www.gong.io",
    "category_slug": "productivity",
    "pricing_model": "paid",
    "pricing_details": "Enterprise pricing based on seats and modules; typically sold to mid-market and enterprise sales organizations.",
    "editor_rating": 4.6,
    "company_name": "Gong",
    "founded_year": 2015,
    "key_features": ["Call recording and transcription", "Deal intelligence", "Coaching and scorecards", "CRM integrations", "Pipeline analytics"],
    "pros": ["Deep sales analytics beyond basic meeting notes", "Strong ROI for mature sales orgs"],
    "cons": ["Expensive for small teams", "Overkill if you only need transcripts"],
    "use_cases": ["Sales coaching", "Forecast review", "Win-loss analysis", "Enablement programs"],
    "who_its_for": ["Sales leaders", "RevOps", "Enterprise sales teams", "Customer success at scale"]
  },
  {
    "slug": "zendesk-ai",
    "name": "Zendesk AI",
    "tagline": "AI agents and copilot features for customer support in Zendesk Suite.",
    "description": "Zendesk AI adds intelligent triage, suggested replies, generative answers, and autonomous agents to the Zendesk support platform. It is built for teams already on Zendesk who want AI-assisted resolution without replacing their ticketing stack.",
    "website_url": "https://www.zendesk.com/service/ai/",
    "category_slug": "ai-agents",
    "pricing_model": "paid",
    "pricing_details": "Included or add-on depending on Zendesk Suite plan; Advanced AI and autonomous agent features typically require higher tiers.",
    "editor_rating": 4.3,
    "company_name": "Zendesk",
    "founded_year": 2007,
    "key_features": ["AI agents for support", "Suggested replies", "Intent detection", "Knowledge base grounding", "Admin and analytics controls"],
    "pros": ["Native fit for existing Zendesk customers", "Enterprise-grade support workflows"],
    "cons": ["Less useful outside Zendesk ecosystem", "Advanced AI can add meaningful cost"],
    "use_cases": ["Ticket deflection", "Agent assist", "Support automation", "Help center answers"],
    "who_its_for": ["Support teams on Zendesk", "Enterprise customer service", "Ops leaders scaling support"]
  },
  {
    "slug": "spellbook",
    "name": "Spellbook",
    "tagline": "AI contract drafting and review copilot for legal teams in Microsoft Word.",
    "description": "Spellbook by Rally helps lawyers draft, review, and redline contracts inside Microsoft Word using AI trained on legal workflows. It suggests clauses, flags risky language, and accelerates first-pass contract work.",
    "website_url": "https://www.spellbook.legal",
    "category_slug": "productivity",
    "pricing_model": "paid",
    "pricing_details": "Subscription pricing for legal teams; trials available; enterprise plans for larger firms.",
    "editor_rating": 4.4,
    "company_name": "Rally",
    "founded_year": 2022,
    "key_features": ["Word-native contract drafting", "Clause suggestions", "Redline assistance", "Playbook alignment", "Multi-jurisdiction templates"],
    "pros": ["Fits existing lawyer workflows in Word", "Useful for contract-heavy teams"],
    "cons": ["Requires human legal review", "Not a replacement for firm-specific judgment"],
    "use_cases": ["Contract drafting", "NDA review", "Vendor agreements", "Legal ops acceleration"],
    "who_its_for": ["In-house legal teams", "Law firms", "Founders reviewing standard agreements"]
  },
  {
    "slug": "pi-ai",
    "name": "Pi",
    "tagline": "Personal AI assistant from Inflection focused on conversational, empathetic chat.",
    "description": "Pi is a consumer AI assistant designed for friendly, supportive conversation, brainstorming, and everyday guidance. Available on web and mobile, it targets users who want a more personal assistant experience than generic chatbots.",
    "website_url": "https://pi.ai",
    "category_slug": "chatbots-assistants",
    "pricing_model": "free",
    "pricing_details": "Free to use; availability and features may vary by region and platform.",
    "editor_rating": 4.2,
    "company_name": "Inflection AI",
    "founded_year": 2022,
    "key_features": ["Conversational assistant", "Mobile and web apps", "Voice interaction", "Personalized tone", "Everyday task support"],
    "pros": ["Accessible and approachable UX", "Strong for casual brainstorming and coaching-style chat"],
    "cons": ["Less workflow depth than ChatGPT or Claude for work tasks", "Not built for enterprise deployment"],
    "use_cases": ["Personal coaching", "Brainstorming", "Daily planning", "Casual Q&A"],
    "who_its_for": ["Consumers", "Students", "Anyone wanting a friendly AI companion"]
  },
  {
    "slug": "activepieces",
    "name": "Activepieces",
    "tagline": "Open-source Zapier alternative with AI steps and self-hosting for automations.",
    "description": "Activepieces is an open-source automation platform for connecting apps, running workflows, and embedding AI steps. It appeals to teams that want Make or Zapier-like automation with more control, self-hosting, and transparent pricing.",
    "website_url": "https://www.activepieces.com",
    "category_slug": "ai-agents",
    "pricing_model": "freemium",
    "pricing_details": "Free self-hosted Community Edition; cloud plans with task limits; enterprise options for SSO and support.",
    "editor_rating": 4.3,
    "company_name": "Activepieces",
    "founded_year": 2022,
    "key_features": ["Visual workflow builder", "400+ integrations", "AI workflow steps", "Self-hosting", "Embeddable automations"],
    "pros": ["Open-source with active community", "Competitive alternative to Zapier and Make"],
    "cons": ["Smaller integration catalog than Zapier", "Self-hosting needs technical setup"],
    "use_cases": ["Business automations", "AI workflow glue", "Internal ops", "SaaS embed scenarios"],
    "who_its_for": ["Developers", "Ops teams", "Startups", "Privacy-conscious organizations"]
  },
  {
    "slug": "semrush-ai",
    "name": "Semrush AI",
    "tagline": "AI writing and SEO toolkit inside the Semrush marketing platform.",
    "description": "Semrush AI bundles content generation, SEO recommendations, keyword insights, and competitive research within Semrush. It is aimed at marketers who already use Semrush for search data and want AI-assisted content workflows in one platform.",
    "website_url": "https://www.semrush.com",
    "category_slug": "writing-content",
    "pricing_model": "paid",
    "pricing_details": "Included with Semrush subscriptions; AI features and limits vary by plan tier.",
    "editor_rating": 4.4,
    "company_name": "Semrush",
    "founded_year": 2008,
    "key_features": ["AI content writing", "SEO recommendations", "Keyword and competitor research", "Content optimization", "Marketing toolkit integration"],
    "pros": ["Combines SEO data with AI writing", "Strong for search-driven content teams"],
    "cons": ["Requires Semrush subscription", "Less flexible as a standalone writing tool"],
    "use_cases": ["SEO blog drafts", "Content briefs", "Competitive research", "On-page optimization"],
    "who_its_for": ["SEO marketers", "Content teams", "Agencies", "Growth marketers"]
  },
  {
    "slug": "jetbrains-ai",
    "name": "JetBrains AI",
    "tagline": "AI assistant built into JetBrains IDEs for chat, completion, and refactoring.",
    "description": "JetBrains AI Assistant integrates generative AI into IntelliJ IDEA, PyCharm, WebStorm, and other JetBrains IDEs. It offers inline completion, chat, explanations, test generation, and commit message help for developers committed to the JetBrains ecosystem.",
    "website_url": "https://www.jetbrains.com/ai/",
    "category_slug": "coding-development",
    "pricing_model": "paid",
    "pricing_details": "Add-on subscription for JetBrains IDE users; bundled options vary by product and organization licensing.",
    "editor_rating": 4.3,
    "company_name": "JetBrains",
    "founded_year": 2000,
    "key_features": ["IDE-native AI chat", "Inline code completion", "Refactoring suggestions", "Test generation", "Commit message assistance"],
    "pros": ["Deep integration with JetBrains IDEs", "Good fit for Java, Kotlin, Python, and WebStorm users"],
    "cons": ["Requires JetBrains subscription stack", "Agent capabilities less aggressive than Cursor"],
    "use_cases": ["Daily coding in JetBrains", "Legacy codebase navigation", "Test writing", "Code explanation"],
    "who_its_for": ["JetBrains IDE users", "Java and Kotlin teams", "Enterprise engineering orgs"]
  },
  {
    "slug": "hippocratic-ai",
    "name": "Hippocratic AI",
    "tagline": "Safety-focused healthcare LLM agents for non-diagnostic clinical workflows.",
    "description": "Hippocratic AI builds large language models and agents designed for healthcare settings with emphasis on safety, compliance, and non-diagnostic use cases such as patient engagement, care navigation, and administrative support.",
    "website_url": "https://www.hippocraticai.com",
    "category_slug": "ai-science-healthcare",
    "pricing_model": "paid",
    "pricing_details": "Enterprise healthcare partnerships; pricing depends on deployment model and use case.",
    "editor_rating": 4.3,
    "company_name": "Hippocratic AI",
    "founded_year": 2023,
    "key_features": ["Healthcare-focused LLM", "Safety-first agent design", "Clinical workflow support", "Enterprise deployment", "Non-diagnostic positioning"],
    "pros": ["Purpose-built for regulated healthcare contexts", "Strong safety narrative vs general chatbots"],
    "cons": ["Not a consumer tool", "Requires institutional evaluation and compliance review"],
    "use_cases": ["Patient follow-up", "Care navigation", "Administrative support", "Clinical trial engagement"],
    "who_its_for": ["Health systems", "Digital health companies", "Clinical ops teams"]
  },
  {
    "slug": "replika",
    "name": "Replika",
    "tagline": "AI companion app for conversation, journaling, and emotional support.",
    "description": "Replika is a consumer AI companion that offers personalized chat, roleplay, journaling prompts, and voice conversations. It is one of the most recognized apps in the AI companion category with a large mobile user base.",
    "website_url": "https://replika.com",
    "category_slug": "chatbots-assistants",
    "pricing_model": "freemium",
    "pricing_details": "Free tier available; Replika Pro unlocks advanced relationship modes, voice calls, and customization.",
    "editor_rating": 4.1,
    "company_name": "Luka",
    "founded_year": 2017,
    "key_features": ["Personalized AI companion", "Voice calls", "Avatar customization", "Journaling and mood tracking", "Mobile-first experience"],
    "pros": ["Large companion community", "Strong mobile UX for daily check-ins"],
    "cons": ["Not suited for factual research or work tasks", "Requires careful use and age-appropriate expectations"],
    "use_cases": ["Companion chat", "Journaling", "Language practice", "Creative roleplay"],
    "who_its_for": ["Consumers", "Mobile users", "People seeking AI companionship"]
  },
  {
    "slug": "hemingway",
    "name": "Hemingway Editor",
    "tagline": "Writing clarity tool that highlights complex sentences and readability issues.",
    "description": "Hemingway Editor helps writers improve clarity by flagging long sentences, passive voice, adverbs, and hard-to-read passages. The Plus version adds AI-powered rewrite suggestions while keeping the focus on readable, direct prose.",
    "website_url": "https://hemingwayapp.com",
    "category_slug": "writing-content",
    "pricing_model": "freemium",
    "pricing_details": "Free online editor; Hemingway Editor Plus adds AI rewrites and desktop apps via subscription.",
    "editor_rating": 4.3,
    "company_name": "Hemingway App",
    "founded_year": 2013,
    "key_features": ["Readability scoring", "Sentence complexity highlights", "AI rewrite suggestions", "Desktop and web editors", "Export-friendly formatting"],
    "pros": ["Simple, focused clarity feedback", "Useful final pass before publishing"],
    "cons": ["Not a full grammar checker like Grammarly", "AI features require paid Plus plan"],
    "use_cases": ["Blog editing", "Email polish", "Documentation clarity", "Marketing copy tightening"],
    "who_its_for": ["Writers", "Bloggers", "Marketers", "Students"]
  },
  {
    "slug": "sudowrite",
    "name": "Sudowrite",
    "tagline": "AI writing partner for fiction authors with story engines and scene tools.",
    "description": "Sudowrite is an AI writing tool built for novelists and fiction writers. It offers story brainstorming, scene expansion, character tools, and rewrite modes tuned for creative long-form work rather than marketing copy.",
    "website_url": "https://www.sudowrite.com",
    "category_slug": "writing-content",
    "pricing_model": "paid",
    "pricing_details": "Subscription tiers based on AI credit usage; trials and plans for hobbyists through professional authors.",
    "editor_rating": 4.5,
    "company_name": "Sudowrite",
    "founded_year": 2020,
    "key_features": ["Story Engine", "Scene expansion", "Character and world tools", "Rewrite and describe modes", "Fiction-focused workflows"],
    "pros": ["Best-in-class for fiction workflows", "Strong community of authors"],
    "cons": ["Not ideal for business or SEO writing", "Credit limits can constrain heavy users"],
    "use_cases": ["Novel drafting", "Short fiction", "Worldbuilding", "Writer's block recovery"],
    "who_its_for": ["Fiction authors", "Screenwriters", "Creative writing students"]
  },
  {
    "slug": "clearscope",
    "name": "Clearscope",
    "tagline": "SEO content optimization platform for research-driven editorial teams.",
    "description": "Clearscope helps content teams research topics, grade drafts against search intent, and improve relevance with term recommendations and competitive benchmarks. It is popular with editorial and SEO teams publishing long-form content at scale.",
    "website_url": "https://www.clearscope.io",
    "category_slug": "writing-content",
    "pricing_model": "paid",
    "pricing_details": "Plans based on report credits and user seats; typically starts at professional-team pricing.",
    "editor_rating": 4.5,
    "company_name": "Clearscope",
    "founded_year": 2017,
    "key_features": ["Content grading", "Term recommendations", "SERP-driven briefs", "Google Docs and WordPress integrations", "Team workflows"],
    "pros": ["Excellent for editorial SEO quality", "Clear grading reduces guesswork"],
    "cons": ["Premium pricing for small blogs", "Less generative than Jasper or ChatGPT"],
    "use_cases": ["SEO blog optimization", "Content briefs", "Editorial QA", "Competitive content research"],
    "who_its_for": ["SEO editors", "Content marketing teams", "Agencies", "Publishers"]
  }
]
$tools$::jsonb) AS t(
    slug text,
    name text,
    tagline text,
    description text,
    website_url text,
    category_slug text,
    pricing_model text,
    pricing_details text,
    editor_rating numeric,
    company_name text,
    founded_year int,
    key_features jsonb,
    pros jsonb,
    cons jsonb,
    use_cases jsonb,
    who_its_for jsonb
  )
)
INSERT INTO public.tools (
  name,
  slug,
  tagline,
  description,
  website_url,
  category_id,
  pricing_model,
  pricing_details,
  editor_rating,
  is_verified,
  is_featured,
  status,
  published_at,
  company_name,
  founded_year,
  key_features,
  pros,
  cons,
  use_cases,
  who_its_for,
  meta_title,
  meta_description
)
SELECT
  t.name,
  t.slug,
  t.tagline,
  t.description,
  t.website_url,
  c.id,
  t.pricing_model::pricing_model,
  t.pricing_details,
  t.editor_rating,
  false,
  false,
  'published'::tool_status,
  now(),
  t.company_name,
  t.founded_year,
  ARRAY(SELECT jsonb_array_elements_text(COALESCE(t.key_features, '[]'::jsonb))),
  ARRAY(SELECT jsonb_array_elements_text(COALESCE(t.pros, '[]'::jsonb))),
  ARRAY(SELECT jsonb_array_elements_text(COALESCE(t.cons, '[]'::jsonb))),
  ARRAY(SELECT jsonb_array_elements_text(COALESCE(t.use_cases, '[]'::jsonb))),
  ARRAY(SELECT jsonb_array_elements_text(COALESCE(t.who_its_for, '[]'::jsonb))),
  t.name || ' Review, Pricing, Alternatives | AiCensus',
  left(t.description, 155)
FROM new_tools AS t
JOIN public.categories AS c ON c.slug = t.category_slug
ON CONFLICT (slug) DO UPDATE SET
  name = excluded.name,
  tagline = excluded.tagline,
  description = excluded.description,
  website_url = excluded.website_url,
  category_id = excluded.category_id,
  pricing_model = excluded.pricing_model,
  pricing_details = excluded.pricing_details,
  editor_rating = excluded.editor_rating,
  is_verified = excluded.is_verified,
  is_featured = excluded.is_featured,
  status = excluded.status,
  published_at = COALESCE(public.tools.published_at, excluded.published_at),
  company_name = excluded.company_name,
  founded_year = excluded.founded_year,
  key_features = excluded.key_features,
  pros = excluded.pros,
  cons = excluded.cons,
  use_cases = excluded.use_cases,
  who_its_for = excluded.who_its_for,
  meta_title = excluded.meta_title,
  meta_description = excluded.meta_description,
  updated_at = now();

COMMIT;
