-- AiCensus growth refresh: 32 high-signal tools for video, assistants,
-- productivity, agents, research, coding, infrastructure, and healthcare.

BEGIN;

WITH new_tools AS (
  SELECT *
  FROM jsonb_to_recordset($tools$
[
  {
    "slug": "capcut",
    "name": "CapCut",
    "tagline": "Creator-first video editor with AI captions, templates, effects, and short-form workflows.",
    "description": "CapCut is a video editor from ByteDance built for social-first creators and teams. Its AI features help generate captions, remove backgrounds, clean audio, translate video, resize for platforms, and turn raw footage into polished short-form clips quickly.",
    "website_url": "https://www.capcut.com",
    "category_slug": "video-audio",
    "pricing_model": "freemium",
    "pricing_details": "Free tier available; paid plans unlock more cloud storage, templates, effects, exports, and advanced AI features.",
    "editor_rating": 4.5,
    "company_name": "ByteDance",
    "founded_year": 2020,
    "key_features": ["AI captions and subtitle styling", "Background removal", "Template-based social editing", "Audio cleanup and voice tools", "Cross-platform desktop, mobile, and web editor"],
    "pros": ["Excellent for fast short-form video workflows", "Very accessible for non-editors"],
    "cons": ["Advanced assets and features require paid plans", "Less suited to complex professional post-production"],
    "use_cases": ["TikTok and Reels editing", "Automatic captions", "Creator video repurposing", "Social ad edits", "Lightweight video localization"],
    "who_its_for": ["Creators", "Social media managers", "Small businesses", "Marketing teams"]
  },
  {
    "slug": "veed",
    "name": "VEED",
    "tagline": "Browser-based video editor with AI subtitles, avatars, translation, and recording tools.",
    "description": "VEED is an online video creation platform that combines editing, screen recording, subtitles, translation, AI avatars, text-to-speech, and brand templates. It is built for teams that need fast video production without a traditional editing suite.",
    "website_url": "https://www.veed.io",
    "category_slug": "video-audio",
    "pricing_model": "freemium",
    "pricing_details": "Free tier available with limits; paid plans add higher export quality, more AI usage, brand tools, and team collaboration.",
    "editor_rating": 4.3,
    "company_name": "VEED",
    "founded_year": 2018,
    "key_features": ["AI subtitles", "Video translation and dubbing", "Screen and webcam recording", "AI avatars and text-to-speech", "Brand kits and templates"],
    "pros": ["Runs fully in the browser", "Strong all-in-one toolkit for marketing videos"],
    "cons": ["Free exports are limited", "Heavy projects can feel slower than desktop editors"],
    "use_cases": ["Marketing videos", "Training content", "Social clips", "Subtitling", "Screen-recorded explainers"],
    "who_its_for": ["Marketers", "Educators", "Creators", "Internal communications teams"]
  },
  {
    "slug": "google-flow",
    "name": "Google Flow",
    "tagline": "AI filmmaking tool from Google Labs for creating cinematic scenes with Veo, Imagen, and Gemini.",
    "description": "Google Flow is an AI filmmaking tool from Google Labs that helps creators generate, direct, and assemble video scenes using Google's generative media models. It is aimed at storyboarding, cinematic shot exploration, and prompt-driven video creation.",
    "website_url": "https://labs.google/fx/tools/flow",
    "category_slug": "video-audio",
    "pricing_model": "freemium",
    "pricing_details": "Availability and usage limits depend on Google Labs rollout, region, account, and plan.",
    "editor_rating": 4.2,
    "company_name": "Google",
    "founded_year": 2025,
    "key_features": ["AI video scene generation", "Prompt-driven filmmaking workflow", "Google Veo model integration", "Storyboard-style iteration", "Cinematic shot exploration"],
    "pros": ["Strong Google model ecosystem behind it", "Designed around film-like iteration rather than one-off clips"],
    "cons": ["Availability may vary by region and account", "Still early compared with mature editing tools"],
    "use_cases": ["Storyboarding", "Concept videos", "AI filmmaking", "Creative previsualization", "Short cinematic scenes"],
    "who_its_for": ["Filmmakers", "Creators", "Agencies", "Creative technologists"]
  },
  {
    "slug": "meta-ai",
    "name": "Meta AI",
    "tagline": "Meta's AI assistant across Facebook, Instagram, WhatsApp, Messenger, and the web.",
    "description": "Meta AI is Meta's consumer AI assistant built into its major apps and available on the web. It supports chat, image generation, search-like answers, creative prompts, and everyday assistant workflows with unusually broad distribution through Meta's social platforms.",
    "website_url": "https://www.meta.ai",
    "category_slug": "chatbots-assistants",
    "pricing_model": "free",
    "pricing_details": "Free to use where available; availability and features vary by region, account, and app surface.",
    "editor_rating": 4.1,
    "company_name": "Meta",
    "founded_year": 2023,
    "key_features": ["Assistant across Meta apps", "Image generation", "Web and social discovery", "Conversational Q&A", "Llama model integration"],
    "pros": ["Huge distribution through existing apps", "Easy entry point for casual AI users"],
    "cons": ["Feature set varies by region and app", "Less workflow depth than specialist AI tools"],
    "use_cases": ["Casual assistant tasks", "Social content ideas", "Image generation", "Quick answers", "Messaging workflows"],
    "who_its_for": ["Meta app users", "Creators", "Casual AI users", "Social media managers"]
  },
  {
    "slug": "character-ai",
    "name": "Character.AI",
    "tagline": "AI character chat platform for roleplay, entertainment, tutoring, and companion-style conversations.",
    "description": "Character.AI is a consumer AI chat platform where users create and talk with fictional, historical, educational, and custom characters. It is one of the most recognizable AI companion and entertainment products, with mobile apps and a large user-created character ecosystem.",
    "website_url": "https://character.ai",
    "category_slug": "chatbots-assistants",
    "pricing_model": "freemium",
    "pricing_details": "Free tier available; paid plans typically add faster responses, priority access, and extra features.",
    "editor_rating": 4.2,
    "company_name": "Character.AI",
    "founded_year": 2021,
    "key_features": ["User-created AI characters", "Roleplay and entertainment chats", "Mobile apps", "Voice-enabled conversations", "Character discovery ecosystem"],
    "pros": ["Large character community", "Strong fit for entertainment and companion use cases"],
    "cons": ["Not designed for factual research", "Safety and age-appropriate use require care"],
    "use_cases": ["Roleplay", "Creative writing", "Language practice", "Entertainment chats", "AI companions"],
    "who_its_for": ["Consumers", "Writers", "Roleplay communities", "Language learners"]
  },
  {
    "slug": "poe",
    "name": "Poe",
    "tagline": "Multi-model AI chat app for trying top bots, custom assistants, and creator-built chatbots.",
    "description": "Poe by Quora is a multi-model AI chat platform that lets users access many AI models and custom bots in one place. It is useful for comparing model behavior, building lightweight bots, and switching between assistants without juggling separate subscriptions.",
    "website_url": "https://poe.com",
    "category_slug": "chatbots-assistants",
    "pricing_model": "freemium",
    "pricing_details": "Free access available with limits; subscriptions add more compute points and access to higher-cost models.",
    "editor_rating": 4.2,
    "company_name": "Quora",
    "founded_year": 2022,
    "key_features": ["Multi-model chat", "Custom bot creation", "Bot marketplace", "Mobile and web apps", "Subscription-based compute points"],
    "pros": ["Convenient way to compare models", "Easy custom bot publishing"],
    "cons": ["Model availability and limits change over time", "Less integrated into work tools than single-vendor assistants"],
    "use_cases": ["Model comparison", "Custom assistants", "Casual AI chat", "Prompt testing", "Bot discovery"],
    "who_its_for": ["AI enthusiasts", "Creators", "Students", "Prompt builders"]
  },
  {
    "slug": "picsart",
    "name": "Picsart",
    "tagline": "AI-powered photo, design, and content editing suite for creators and small teams.",
    "description": "Picsart is a creative platform for editing photos, making designs, generating images, removing backgrounds, creating social assets, and producing branded visuals. Its AI tools make quick creative production accessible from web and mobile surfaces.",
    "website_url": "https://picsart.com",
    "category_slug": "design-creative",
    "pricing_model": "freemium",
    "pricing_details": "Free tier available; paid plans add premium templates, assets, exports, and more AI capacity.",
    "editor_rating": 4.2,
    "company_name": "Picsart",
    "founded_year": 2011,
    "key_features": ["AI image generation", "Photo editing", "Background removal", "Design templates", "Mobile and web creative tools"],
    "pros": ["Accessible creative workflow for non-designers", "Strong mobile editing experience"],
    "cons": ["Premium assets require paid plans", "Less precise than professional design suites"],
    "use_cases": ["Social graphics", "Photo cleanup", "Ad creative", "Creator thumbnails", "Small business design"],
    "who_its_for": ["Creators", "Small businesses", "Social teams", "Non-designers"]
  },
  {
    "slug": "napkin-ai",
    "name": "Napkin AI",
    "tagline": "Turn text into diagrams, visuals, and presentation-ready business graphics.",
    "description": "Napkin AI converts written ideas into editable visuals such as diagrams, frameworks, flowcharts, and presentation graphics. It is useful when teams need to make strategic, product, or educational concepts more visual without opening a full design tool.",
    "website_url": "https://www.napkin.ai",
    "category_slug": "design-creative",
    "pricing_model": "freemium",
    "pricing_details": "Free access available with limits; paid plans may add more exports, collaboration, and advanced features.",
    "editor_rating": 4.3,
    "company_name": "Napkin AI",
    "founded_year": 2023,
    "key_features": ["Text-to-visual generation", "Editable diagrams", "Presentation graphics", "Concept maps", "Exportable visuals"],
    "pros": ["Great for turning messy ideas into clear visuals", "Much faster than designing diagrams manually"],
    "cons": ["Best for business visuals, not full design systems", "Outputs still need editorial judgment"],
    "use_cases": ["Strategy diagrams", "Presentation visuals", "Product explainers", "Educational graphics", "Meeting artifacts"],
    "who_its_for": ["Founders", "Product managers", "Consultants", "Educators"]
  },
  {
    "slug": "recraft",
    "name": "Recraft",
    "tagline": "AI design tool for vector art, illustrations, icons, mockups, and brand-consistent visuals.",
    "description": "Recraft is an AI image and design tool focused on controllable graphics, vector-style assets, illustrations, icons, and brand-consistent visual systems. It is useful for designers and marketers who need editable, production-friendly visuals rather than only prompt-generated images.",
    "website_url": "https://www.recraft.ai",
    "category_slug": "image-generation",
    "pricing_model": "freemium",
    "pricing_details": "Free tier available; paid plans add more generation capacity, privacy, exports, and commercial workflow features.",
    "editor_rating": 4.3,
    "company_name": "Recraft",
    "founded_year": 2022,
    "key_features": ["AI image generation", "Vector and icon-style outputs", "Brand style controls", "Mockups and design assets", "Editable creative workflows"],
    "pros": ["Better fit for design assets than generic image generators", "Strong control for brand-consistent visuals"],
    "cons": ["Not always the best choice for photorealism", "Advanced workflows require experimentation"],
    "use_cases": ["Icons", "Illustrations", "Brand visuals", "Ad creative", "Mockups"],
    "who_its_for": ["Designers", "Marketers", "Brand teams", "Creative agencies"]
  },
  {
    "slug": "magnific-ai",
    "name": "Magnific AI",
    "tagline": "AI image upscaler and enhancer for adding detail, texture, and resolution.",
    "description": "Magnific AI is an AI image enhancement platform known for creative upscaling, detail recovery, and texture-rich transformations. It helps artists, photographers, and creators turn lower-resolution or rough generated images into more polished, high-resolution assets.",
    "website_url": "https://magnific.ai",
    "category_slug": "image-generation",
    "pricing_model": "paid",
    "pricing_details": "Paid plans with usage limits; pricing and credit allowances vary by plan.",
    "editor_rating": 4.2,
    "company_name": "Magnific AI",
    "founded_year": 2023,
    "key_features": ["AI upscaling", "Detail enhancement", "Creative image refinement", "Style-preserving transformations", "High-resolution exports"],
    "pros": ["Excellent for adding detail to generated images", "Useful bridge from draft image to polished asset"],
    "cons": ["Can over-invent details if pushed too far", "Paid-only model limits casual use"],
    "use_cases": ["Image upscaling", "AI art finishing", "Product visual enhancement", "Concept art polish", "Print-ready assets"],
    "who_its_for": ["Artists", "Designers", "Photographers", "AI image creators"]
  },
  {
    "slug": "topaz-labs",
    "name": "Topaz Labs",
    "tagline": "AI photo and video enhancement tools for upscaling, denoising, sharpening, and recovery.",
    "description": "Topaz Labs builds AI-powered image and video enhancement software for photographers, filmmakers, and creative professionals. Its tools help upscale footage, reduce noise, sharpen images, stabilize video, and recover detail from imperfect source media.",
    "website_url": "https://www.topazlabs.com",
    "category_slug": "image-generation",
    "pricing_model": "paid",
    "pricing_details": "Paid desktop apps and upgrades; pricing varies by product and bundle.",
    "editor_rating": 4.4,
    "company_name": "Topaz Labs",
    "founded_year": 2005,
    "key_features": ["AI image upscaling", "Video enhancement", "Noise reduction", "Sharpening and restoration", "Desktop creative workflow"],
    "pros": ["Professional-grade enhancement quality", "Useful for both photo and video workflows"],
    "cons": ["Requires desktop hardware and paid licenses", "Not a prompt-to-image generator"],
    "use_cases": ["Photo restoration", "Video upscaling", "Noise reduction", "Creative finishing", "Archive enhancement"],
    "who_its_for": ["Photographers", "Video editors", "Archivists", "Creative professionals"]
  },
  {
    "slug": "fathom",
    "name": "Fathom",
    "tagline": "AI meeting assistant for recording, transcribing, summarizing, and syncing calls.",
    "description": "Fathom is an AI meeting assistant that records calls, creates transcripts, highlights key moments, summarizes decisions, and syncs notes into tools like CRM and collaboration systems. It is popular with sales, customer success, and operations teams.",
    "website_url": "https://fathom.video",
    "category_slug": "productivity",
    "pricing_model": "freemium",
    "pricing_details": "Free individual plan available; paid team plans add collaboration, integrations, and administrative controls.",
    "editor_rating": 4.4,
    "company_name": "Fathom",
    "founded_year": 2020,
    "key_features": ["Meeting recording", "AI summaries", "Transcripts and highlights", "CRM sync", "Team collaboration"],
    "pros": ["Strong free individual plan", "Great for customer-facing meeting workflows"],
    "cons": ["Bot-based meeting capture may not fit every culture", "Team features require paid plans"],
    "use_cases": ["Sales calls", "Customer interviews", "Meeting notes", "CRM updates", "Follow-up summaries"],
    "who_its_for": ["Sales teams", "Customer success teams", "Founders", "Product teams"]
  },
  {
    "slug": "fireflies-ai",
    "name": "Fireflies.ai",
    "tagline": "AI meeting notetaker for transcripts, summaries, search, and conversation intelligence.",
    "description": "Fireflies.ai records and transcribes meetings, generates summaries, extracts action items, and makes conversations searchable across teams. It supports major meeting platforms and is useful for organizations that want a searchable memory of calls.",
    "website_url": "https://fireflies.ai",
    "category_slug": "productivity",
    "pricing_model": "freemium",
    "pricing_details": "Free plan available with limits; paid plans add more transcription, storage, integrations, and team controls.",
    "editor_rating": 4.2,
    "company_name": "Fireflies.ai",
    "founded_year": 2016,
    "key_features": ["Meeting transcription", "AI summaries", "Action item extraction", "Conversation search", "CRM and collaboration integrations"],
    "pros": ["Broad meeting platform support", "Strong searchable meeting archive"],
    "cons": ["Accuracy depends on audio quality", "Bot attendance can feel intrusive in some meetings"],
    "use_cases": ["Meeting notes", "Sales intelligence", "Interview transcription", "Team knowledge capture", "Action item tracking"],
    "who_its_for": ["Remote teams", "Sales teams", "Recruiters", "Product managers"]
  },
  {
    "slug": "tl-dv",
    "name": "tl;dv",
    "tagline": "AI meeting recorder for highlights, summaries, clips, and searchable customer calls.",
    "description": "tl;dv is an AI meeting recorder and intelligence tool that captures calls, creates summaries, clips important moments, and helps teams search across meeting history. It is especially useful for product, sales, and customer research teams reviewing large volumes of calls.",
    "website_url": "https://tldv.io",
    "category_slug": "productivity",
    "pricing_model": "freemium",
    "pricing_details": "Free tier available; paid plans add more AI features, integrations, team controls, and storage.",
    "editor_rating": 4.2,
    "company_name": "tl;dv",
    "founded_year": 2020,
    "key_features": ["Meeting recording", "AI summaries", "Clip sharing", "Transcript search", "CRM and collaboration integrations"],
    "pros": ["Great for sharing call moments", "Useful for customer research repositories"],
    "cons": ["Some advanced intelligence features require paid plans", "Best value appears with consistent meeting volume"],
    "use_cases": ["Customer calls", "User interviews", "Sales reviews", "Meeting highlights", "Team knowledge sharing"],
    "who_its_for": ["Product teams", "Sales teams", "Customer success", "Researchers"]
  },
  {
    "slug": "read-ai",
    "name": "Read AI",
    "tagline": "AI meeting and email summaries with productivity analytics across workplace communication.",
    "description": "Read AI summarizes meetings, messages, and email threads while providing productivity analytics for workplace communication. It helps teams turn scattered conversations into searchable summaries, action items, and follow-up context.",
    "website_url": "https://www.read.ai",
    "category_slug": "productivity",
    "pricing_model": "freemium",
    "pricing_details": "Free access available with limits; paid plans add more reports, integrations, and team features.",
    "editor_rating": 4.1,
    "company_name": "Read AI",
    "founded_year": 2021,
    "key_features": ["Meeting summaries", "Email and message summaries", "Action item extraction", "Productivity analytics", "Workplace integrations"],
    "pros": ["Covers more than meetings", "Useful for reducing communication catch-up time"],
    "cons": ["Analytics may feel sensitive without clear team norms", "Integrations and limits vary by plan"],
    "use_cases": ["Meeting recaps", "Email catch-up", "Team communication summaries", "Action tracking", "Productivity reporting"],
    "who_its_for": ["Managers", "Remote teams", "Executives", "Operations teams"]
  },
  {
    "slug": "motion",
    "name": "Motion",
    "tagline": "AI calendar and project planner that schedules tasks around meetings and deadlines.",
    "description": "Motion is an AI productivity app that automatically plans tasks, projects, and meetings onto a calendar. It helps users prioritize work, reschedule around interruptions, and keep personal or team execution plans realistic.",
    "website_url": "https://www.usemotion.com",
    "category_slug": "productivity",
    "pricing_model": "paid",
    "pricing_details": "Paid plans for individuals and teams; trial availability and plan limits can vary.",
    "editor_rating": 4.2,
    "company_name": "Motion",
    "founded_year": 2019,
    "key_features": ["AI task scheduling", "Calendar planning", "Project management", "Meeting booking", "Automatic rescheduling"],
    "pros": ["Strong for time-blocking real work", "Combines tasks and calendar in one planning loop"],
    "cons": ["Requires trust in automated scheduling", "Can feel heavy if your calendar is already highly structured"],
    "use_cases": ["Daily planning", "Project scheduling", "Focus time protection", "Team workload planning", "Task prioritization"],
    "who_its_for": ["Founders", "Managers", "Busy professionals", "Small teams"]
  },
  {
    "slug": "superhuman",
    "name": "Superhuman",
    "tagline": "Premium email client with AI drafting, triage, summaries, and fast keyboard workflows.",
    "description": "Superhuman is a premium email client built around speed, keyboard shortcuts, triage, and polished workflows. Its AI features help draft replies, summarize long threads, improve tone, and move through inbox-heavy work faster.",
    "website_url": "https://superhuman.com",
    "category_slug": "productivity",
    "pricing_model": "paid",
    "pricing_details": "Paid subscription; team and business pricing vary by seat and plan.",
    "editor_rating": 4.3,
    "company_name": "Superhuman",
    "founded_year": 2014,
    "key_features": ["AI email drafting", "Thread summaries", "Keyboard-first inbox", "Follow-up reminders", "Team collaboration features"],
    "pros": ["Extremely fast email workflow", "AI features fit naturally into inbox work"],
    "cons": ["Premium pricing is not for casual email users", "Best for Gmail and Outlook-centric workflows"],
    "use_cases": ["Inbox triage", "Sales email", "Executive communication", "Follow-up management", "Thread summarization"],
    "who_its_for": ["Executives", "Founders", "Sales teams", "Inbox-heavy professionals"]
  },
  {
    "slug": "shortwave",
    "name": "Shortwave",
    "tagline": "AI email app for summarizing, searching, drafting, and organizing Gmail-heavy workflows.",
    "description": "Shortwave is an AI email client built for Gmail users who want smarter search, summaries, drafting, bundles, and team-friendly inbox workflows. It turns email threads into faster, more structured work without leaving the inbox.",
    "website_url": "https://www.shortwave.com",
    "category_slug": "productivity",
    "pricing_model": "freemium",
    "pricing_details": "Free tier available with limits; paid plans add more AI usage, history, team features, and administrative controls.",
    "editor_rating": 4.2,
    "company_name": "Shortwave",
    "founded_year": 2020,
    "key_features": ["AI email summaries", "AI search", "Drafting assistance", "Inbox bundles", "Team inbox workflows"],
    "pros": ["Strong Gmail-native productivity layer", "AI search is useful for buried context"],
    "cons": ["Gmail-focused", "Advanced AI and history features require paid plans"],
    "use_cases": ["Email search", "Thread summaries", "Inbox organization", "Drafting replies", "Team email workflows"],
    "who_its_for": ["Gmail power users", "Founders", "Support teams", "Knowledge workers"]
  },
  {
    "slug": "harvey",
    "name": "Harvey",
    "tagline": "AI platform for legal professionals handling research, drafting, analysis, and workflows.",
    "description": "Harvey is an AI platform built for law firms and legal teams. It assists with legal research, drafting, document analysis, due diligence, and specialized workflows while emphasizing enterprise controls for professional legal environments.",
    "website_url": "https://www.harvey.ai",
    "category_slug": "productivity",
    "pricing_model": "enterprise",
    "pricing_details": "Enterprise pricing is custom and depends on organization size, deployment, security, and workflow requirements.",
    "editor_rating": 4.4,
    "company_name": "Harvey",
    "founded_year": 2022,
    "key_features": ["Legal research assistance", "Document drafting", "Due diligence workflows", "Enterprise security controls", "Law-firm-focused AI"],
    "pros": ["Purpose-built for legal work", "Strong fit for enterprise legal teams"],
    "cons": ["Not aimed at casual users", "Requires careful professional review of all outputs"],
    "use_cases": ["Legal research", "Contract analysis", "Due diligence", "Drafting", "Matter workflows"],
    "who_its_for": ["Law firms", "In-house counsel", "Legal operations", "Professional services firms"]
  },
  {
    "slug": "lindy",
    "name": "Lindy",
    "tagline": "No-code AI agents for email, scheduling, research, CRM updates, and operations work.",
    "description": "Lindy is an AI agent platform for building assistants that handle repetitive knowledge work such as email triage, scheduling, research, CRM updates, and workflow automation. It is designed for non-technical teams that want configurable agents across daily tools.",
    "website_url": "https://www.lindy.ai",
    "category_slug": "ai-agents",
    "pricing_model": "freemium",
    "pricing_details": "Free or trial access may be available; paid plans add more agent usage, integrations, and team controls.",
    "editor_rating": 4.3,
    "company_name": "Lindy",
    "founded_year": 2023,
    "key_features": ["No-code AI agents", "Email and calendar automation", "Research workflows", "CRM updates", "App integrations"],
    "pros": ["Approachable agent builder for operations work", "Strong fit for repeatable admin workflows"],
    "cons": ["Agent reliability depends on workflow design", "Sensitive actions need human review and permissions"],
    "use_cases": ["Email triage", "Scheduling", "Lead research", "CRM automation", "Operations assistants"],
    "who_its_for": ["Founders", "Sales teams", "Operations teams", "Executive assistants"]
  },
  {
    "slug": "salesforce-agentforce",
    "name": "Salesforce Agentforce",
    "tagline": "Salesforce's platform for building AI agents over CRM, service, sales, and enterprise workflows.",
    "description": "Salesforce Agentforce is an enterprise AI agent platform for creating agents that operate across Salesforce data, customer service, sales, marketing, and business workflows. It is designed for organizations that want AI agents grounded in CRM context and enterprise governance.",
    "website_url": "https://www.salesforce.com/agentforce/",
    "category_slug": "ai-agents",
    "pricing_model": "enterprise",
    "pricing_details": "Enterprise pricing depends on Salesforce products, seats, usage, data, and deployment requirements.",
    "editor_rating": 4.3,
    "company_name": "Salesforce",
    "founded_year": 2024,
    "key_features": ["CRM-grounded AI agents", "Service and sales workflows", "Enterprise governance", "Salesforce data integration", "Agent builder tools"],
    "pros": ["Deep Salesforce ecosystem fit", "Strong enterprise data and governance story"],
    "cons": ["Most useful inside Salesforce-heavy organizations", "Implementation requires admin and process design"],
    "use_cases": ["Customer service agents", "Sales assistants", "CRM automation", "Case handling", "Enterprise workflow agents"],
    "who_its_for": ["Enterprises", "Salesforce admins", "Sales teams", "Service teams"]
  },
  {
    "slug": "sierra",
    "name": "Sierra",
    "tagline": "Conversational AI agents for customer service, support, and brand-safe customer experiences.",
    "description": "Sierra builds AI agents for customer service and support workflows. Its platform helps businesses create branded conversational agents that can answer questions, take actions, escalate issues, and operate within customer experience guardrails.",
    "website_url": "https://www.sierra.ai",
    "category_slug": "ai-agents",
    "pricing_model": "enterprise",
    "pricing_details": "Enterprise pricing is custom and depends on volume, integrations, deployment, and support requirements.",
    "editor_rating": 4.4,
    "company_name": "Sierra",
    "founded_year": 2023,
    "key_features": ["Customer service AI agents", "Brand voice controls", "Action-taking workflows", "Escalation handling", "Enterprise integrations"],
    "pros": ["Focused on customer-facing agent reliability", "Strong positioning for large support organizations"],
    "cons": ["Enterprise-only fit", "Requires integration with existing support and data systems"],
    "use_cases": ["Customer support", "Order help", "Account service", "Support deflection", "Customer experience automation"],
    "who_its_for": ["Enterprises", "Support teams", "CX leaders", "Operations teams"]
  },
  {
    "slug": "intercom-fin",
    "name": "Intercom Fin",
    "tagline": "AI customer support agent for resolving support questions across help centers and conversations.",
    "description": "Intercom Fin is an AI support agent built into Intercom for answering customer questions, resolving support issues, escalating to teammates, and using help center or business content as source material.",
    "website_url": "https://www.intercom.com/fin",
    "category_slug": "ai-agents",
    "pricing_model": "paid",
    "pricing_details": "Paid Intercom product with pricing based on seats, resolutions, plan, and support setup.",
    "editor_rating": 4.3,
    "company_name": "Intercom",
    "founded_year": 2023,
    "key_features": ["AI support agent", "Help center grounding", "Conversation handoff", "Resolution tracking", "Intercom inbox integration"],
    "pros": ["Natural fit for existing Intercom customers", "Designed around measurable support resolutions"],
    "cons": ["Tied to Intercom's platform", "Requires high-quality support content to perform well"],
    "use_cases": ["Support deflection", "Help center Q&A", "Customer service automation", "Ticket triage", "Live chat assistance"],
    "who_its_for": ["Support teams", "SaaS companies", "Customer success teams", "Operations teams"]
  },
  {
    "slug": "decagon",
    "name": "Decagon",
    "tagline": "Enterprise AI agents for customer support, operations, and high-volume service workflows.",
    "description": "Decagon builds AI agents for enterprise customer support and operational workflows. Its platform focuses on resolving customer issues, integrating with business systems, and giving support leaders visibility into agent performance.",
    "website_url": "https://decagon.ai",
    "category_slug": "ai-agents",
    "pricing_model": "enterprise",
    "pricing_details": "Enterprise pricing is custom and depends on support volume, integrations, deployment, and controls.",
    "editor_rating": 4.2,
    "company_name": "Decagon",
    "founded_year": 2023,
    "key_features": ["Customer support AI agents", "Business system integrations", "Resolution analytics", "Human escalation", "Enterprise deployment controls"],
    "pros": ["Built for high-volume support teams", "Strong focus on operational outcomes"],
    "cons": ["Enterprise implementation effort required", "Not a general-purpose agent builder"],
    "use_cases": ["Customer support automation", "Ticket resolution", "Operational workflows", "Support analytics", "Customer experience scaling"],
    "who_its_for": ["Enterprises", "Support leaders", "Operations teams", "Customer experience teams"]
  },
  {
    "slug": "langgraph",
    "name": "LangGraph",
    "tagline": "Framework for building stateful, controllable AI agents and multi-step LLM workflows.",
    "description": "LangGraph is a framework from LangChain for building stateful agent workflows, graph-based control flow, human-in-the-loop systems, and durable multi-step LLM applications. It is popular with developers who need more control than a simple chain or chatbot.",
    "website_url": "https://www.langchain.com/langgraph",
    "category_slug": "ai-agents",
    "pricing_model": "open_source",
    "pricing_details": "Open-source framework; managed platform, hosting, tracing, and enterprise features may be paid through LangChain.",
    "editor_rating": 4.5,
    "company_name": "LangChain",
    "founded_year": 2024,
    "key_features": ["Stateful agent graphs", "Human-in-the-loop control", "Multi-agent workflows", "Persistence and interrupts", "LangChain ecosystem integration"],
    "pros": ["Strong control model for real agent systems", "Good fit for production-grade workflow orchestration"],
    "cons": ["Requires engineering skill", "Can be more complex than simple agent builders"],
    "use_cases": ["Agent orchestration", "Workflow automation", "Human-reviewed agents", "Multi-step LLM apps", "Research assistants"],
    "who_its_for": ["AI engineers", "Agent builders", "Backend developers", "Product teams"]
  },
  {
    "slug": "clay",
    "name": "Clay",
    "tagline": "AI-powered go-to-market data enrichment and prospecting workspace.",
    "description": "Clay is a sales and growth platform for finding leads, enriching company and contact data, researching prospects with AI, and building outbound workflows. It combines data providers, AI agents, and spreadsheet-like workflows for modern go-to-market teams.",
    "website_url": "https://www.clay.com",
    "category_slug": "data-analytics",
    "pricing_model": "freemium",
    "pricing_details": "Free or starter access may be available; paid plans and credits depend on enrichment usage, providers, and team needs.",
    "editor_rating": 4.4,
    "company_name": "Clay",
    "founded_year": 2017,
    "key_features": ["Lead enrichment", "AI prospect research", "Data provider integrations", "Outbound workflow tables", "CRM and sales tooling integrations"],
    "pros": ["Excellent for GTM research and enrichment workflows", "Flexible spreadsheet-like interface"],
    "cons": ["Credit costs can climb with heavy enrichment", "Requires careful data quality and deliverability practices"],
    "use_cases": ["Sales prospecting", "Lead enrichment", "Account research", "Outbound personalization", "GTM data workflows"],
    "who_its_for": ["Sales teams", "Growth teams", "Founders", "RevOps teams"]
  },
  {
    "slug": "hebbia",
    "name": "Hebbia",
    "tagline": "AI research and analysis platform for financial, legal, and professional-services documents.",
    "description": "Hebbia is an AI research platform for analyzing large sets of documents and extracting structured answers from complex materials. It is used in finance, legal, consulting, and professional services workflows where source-grounded analysis matters.",
    "website_url": "https://www.hebbia.ai",
    "category_slug": "research-search",
    "pricing_model": "enterprise",
    "pricing_details": "Enterprise pricing is custom and depends on users, data volume, security, and deployment requirements.",
    "editor_rating": 4.3,
    "company_name": "Hebbia",
    "founded_year": 2020,
    "key_features": ["Document research", "Source-grounded answers", "Structured extraction", "Multi-document analysis", "Enterprise security"],
    "pros": ["Strong fit for high-stakes document analysis", "Designed for professional research workflows"],
    "cons": ["Enterprise-focused pricing and onboarding", "Requires quality source data"],
    "use_cases": ["Investment research", "Due diligence", "Legal document review", "Consulting research", "Enterprise knowledge analysis"],
    "who_its_for": ["Investment teams", "Law firms", "Consultants", "Enterprise analysts"]
  },
  {
    "slug": "genspark",
    "name": "Genspark",
    "tagline": "AI search and research engine that generates synthesized pages, answers, and task workflows.",
    "description": "Genspark is an AI search and research product that creates synthesized results and AI-generated pages for user questions. It focuses on turning web research into concise, organized answers and workflows rather than a traditional list of links.",
    "website_url": "https://www.genspark.ai",
    "category_slug": "research-search",
    "pricing_model": "freemium",
    "pricing_details": "Free access available with limits; paid plans may add more advanced usage, models, and agent-style workflows.",
    "editor_rating": 4.1,
    "company_name": "Genspark",
    "founded_year": 2023,
    "key_features": ["AI search", "Generated research pages", "Synthesized web answers", "Task-oriented research workflows", "Source-backed exploration"],
    "pros": ["Good alternative search experience", "Useful for structured research summaries"],
    "cons": ["Source quality still needs verification", "Less established than Perplexity or Google"],
    "use_cases": ["Web research", "Topic summaries", "Product comparisons", "Travel and shopping research", "Answer engine workflows"],
    "who_its_for": ["Researchers", "Students", "Knowledge workers", "Curious consumers"]
  },
  {
    "slug": "openevidence",
    "name": "OpenEvidence",
    "tagline": "AI medical search and clinical evidence assistant for healthcare professionals.",
    "description": "OpenEvidence is an AI medical search and evidence platform built for clinicians and healthcare professionals. It helps users ask clinical questions and review source-grounded medical evidence, summaries, and literature-backed answers.",
    "website_url": "https://www.openevidence.com",
    "category_slug": "ai-science-healthcare",
    "pricing_model": "free",
    "pricing_details": "Free access available for verified medical professionals; availability and verification requirements may vary.",
    "editor_rating": 4.4,
    "company_name": "OpenEvidence",
    "founded_year": 2022,
    "key_features": ["Medical evidence search", "Clinical Q&A", "Source-grounded answers", "Literature summaries", "Healthcare professional verification"],
    "pros": ["Purpose-built for medical evidence lookup", "Source grounding is essential for clinical contexts"],
    "cons": ["Not a substitute for clinical judgment", "Access may depend on professional verification"],
    "use_cases": ["Clinical evidence lookup", "Medical literature review", "Care guideline research", "Healthcare education", "Point-of-care questions"],
    "who_its_for": ["Physicians", "Clinicians", "Medical students", "Healthcare researchers"]
  },
  {
    "slug": "coderabbit",
    "name": "CodeRabbit",
    "tagline": "AI code review assistant for pull requests, summaries, comments, and quality checks.",
    "description": "CodeRabbit is an AI code review tool that reviews pull requests, comments on issues, summarizes changes, and helps teams catch bugs and quality problems earlier. It integrates with code hosting platforms and fits into existing review workflows.",
    "website_url": "https://www.coderabbit.ai",
    "category_slug": "coding-development",
    "pricing_model": "freemium",
    "pricing_details": "Free or trial access may be available; paid plans add private repository, team, and higher-usage features.",
    "editor_rating": 4.3,
    "company_name": "CodeRabbit",
    "founded_year": 2023,
    "key_features": ["AI pull request reviews", "Change summaries", "Line-level comments", "Code quality suggestions", "Git platform integrations"],
    "pros": ["Improves review throughput", "Useful automated second reviewer for busy teams"],
    "cons": ["Still needs human ownership", "Can produce noisy comments without tuning"],
    "use_cases": ["Pull request review", "Code quality checks", "Team review assistance", "Change summaries", "Bug detection"],
    "who_its_for": ["Engineering teams", "Open-source maintainers", "Tech leads", "Startup developers"]
  },
  {
    "slug": "cline",
    "name": "Cline",
    "tagline": "Open-source autonomous coding agent for VS Code with terminal, browser, and file-editing workflows.",
    "description": "Cline is an open-source AI coding agent for VS Code that can inspect projects, edit files, run terminal commands, use browser actions, and work through multi-step software tasks under developer supervision.",
    "website_url": "https://cline.bot",
    "category_slug": "coding-development",
    "pricing_model": "open_source",
    "pricing_details": "Open-source extension; model costs depend on the API or local model provider connected by the user.",
    "editor_rating": 4.4,
    "company_name": "Cline",
    "founded_year": 2024,
    "key_features": ["VS Code coding agent", "Terminal command execution", "File edits", "Browser use", "Bring-your-own-model setup"],
    "pros": ["Open-source and flexible", "Powerful for developer-supervised agent workflows"],
    "cons": ["Requires careful review of actions and costs", "Setup depends on model provider choices"],
    "use_cases": ["Feature implementation", "Bug fixing", "Repo exploration", "Test generation", "Codebase automation"],
    "who_its_for": ["Developers", "Open-source builders", "AI coding enthusiasts", "Technical founders"]
  },
  {
    "slug": "pinecone",
    "name": "Pinecone",
    "tagline": "Managed vector database for semantic search, RAG, recommendations, and AI retrieval.",
    "description": "Pinecone is a managed vector database used for semantic search, retrieval-augmented generation, recommendations, and AI memory. It helps developers store embeddings, query similar content, and build production retrieval systems without operating vector infrastructure themselves.",
    "website_url": "https://www.pinecone.io",
    "category_slug": "models-infrastructure",
    "pricing_model": "freemium",
    "pricing_details": "Free or starter capacity may be available; paid usage depends on storage, throughput, serverless or pod configuration, and scale.",
    "editor_rating": 4.5,
    "company_name": "Pinecone",
    "founded_year": 2019,
    "key_features": ["Managed vector database", "Semantic search", "RAG retrieval", "Metadata filtering", "Scalable production infrastructure"],
    "pros": ["Strong production-ready vector infrastructure", "Developer-friendly for RAG applications"],
    "cons": ["Costs depend on scale and workload", "Requires good embedding and retrieval design"],
    "use_cases": ["RAG systems", "Semantic search", "Recommendations", "AI memory", "Document retrieval"],
    "who_its_for": ["AI engineers", "Backend developers", "ML teams", "AI product companies"]
  }
]
$tools$::jsonb) AS t(
    slug text,
    name text,
    tagline text,
    description text,
    website_url text,
    category_slug text,
    pricing_model text,
    pricing_details text,
    editor_rating numeric,
    company_name text,
    founded_year integer,
    key_features jsonb,
    pros jsonb,
    cons jsonb,
    use_cases jsonb,
    who_its_for jsonb
  )
)
INSERT INTO public.tools (
  name,
  slug,
  tagline,
  description,
  website_url,
  category_id,
  pricing_model,
  pricing_details,
  editor_rating,
  is_verified,
  is_featured,
  status,
  published_at,
  company_name,
  founded_year,
  key_features,
  pros,
  cons,
  use_cases,
  who_its_for,
  meta_title,
  meta_description
)
SELECT
  t.name,
  t.slug,
  t.tagline,
  t.description,
  t.website_url,
  c.id,
  t.pricing_model::pricing_model,
  t.pricing_details,
  t.editor_rating,
  true,
  false,
  'published'::tool_status,
  now(),
  t.company_name,
  t.founded_year,
  ARRAY(SELECT jsonb_array_elements_text(COALESCE(t.key_features, '[]'::jsonb))),
  ARRAY(SELECT jsonb_array_elements_text(COALESCE(t.pros, '[]'::jsonb))),
  ARRAY(SELECT jsonb_array_elements_text(COALESCE(t.cons, '[]'::jsonb))),
  ARRAY(SELECT jsonb_array_elements_text(COALESCE(t.use_cases, '[]'::jsonb))),
  ARRAY(SELECT jsonb_array_elements_text(COALESCE(t.who_its_for, '[]'::jsonb))),
  t.name || ' Review, Pricing, Alternatives | AiCensus',
  left(t.description, 155)
FROM new_tools AS t
JOIN public.categories AS c ON c.slug = t.category_slug
ON CONFLICT (slug) DO UPDATE SET
  name = excluded.name,
  tagline = excluded.tagline,
  description = excluded.description,
  website_url = excluded.website_url,
  category_id = excluded.category_id,
  pricing_model = excluded.pricing_model,
  pricing_details = excluded.pricing_details,
  editor_rating = excluded.editor_rating,
  is_verified = excluded.is_verified,
  is_featured = excluded.is_featured,
  status = excluded.status,
  published_at = COALESCE(public.tools.published_at, excluded.published_at),
  company_name = excluded.company_name,
  founded_year = excluded.founded_year,
  key_features = excluded.key_features,
  pros = excluded.pros,
  cons = excluded.cons,
  use_cases = excluded.use_cases,
  who_its_for = excluded.who_its_for,
  meta_title = excluded.meta_title,
  meta_description = excluded.meta_description,
  updated_at = now();

COMMIT;
