-- Q2 2026 catalog accuracy refresh from three-agent fact-check pass (FC1/FC2/FC3).
-- Updates stale pricing, positioning, and archives discontinued products.

BEGIN;

WITH updates AS (
  SELECT *
  FROM jsonb_to_recordset($updates$
[
  {"slug":"phind","status":"archived","tagline":"Former AI search engine for developers (shut down January 2026).","description":"Phind was an AI-powered developer search engine with cited answers and code-focused chat. The service shut down on January 16, 2026; phind.com is offline and user data was deleted by January 30, 2026.","pricing_model":"free","pricing_details":"Service discontinued January 16, 2026. Former Pro plan was ~$17/month; no subscriptions remain available."},
  {"slug":"socratic","status":"archived","website_url":"https://lens.google/","tagline":"Discontinued Google homework app; features live in Google Lens.","description":"Socratic by Google was a free homework-help app using AI to explain math, science, and other subjects. The standalone app was delisted in 2024 and its functionality was merged into Google Lens and the Google app.","pricing_model":"free","pricing_details":"Free where available through Google Lens homework features; the standalone Socratic app is no longer distributed."},
  {"slug":"copy-ai","pricing_model":"freemium","pricing_details":"Free tier with limited words; Chat from ~$36–49/mo; Growth $1,000/mo; Expansion $2,000/mo; Scale $3,000/mo; Enterprise custom.","tagline":"GTM AI platform for sales, marketing, content, and workflow automation.","description":"Copy.ai is a go-to-market AI platform for automating sales, marketing, and ops workflows with multi-model chat, workflow builder, and 2,000+ integrations. It has moved beyond copywriting into team-scale GTM automation."},
  {"slug":"surfer-seo","pricing_details":"Discovery from $49/mo (annual); Standard $99/mo; Pro $182/mo; Peace of Mind $299/mo; Enterprise from $999/mo. Legacy Essential/Scale plan names were retired in 2025–2026.","tagline":"AI SEO content platform with Content Editor, site audits, and AI search visibility tracking.","description":"Surfer SEO helps teams optimize articles for Google and AI search with real-time content scoring, SERP analysis, topical maps, and AI visibility tracking. Plans were rebranded in 2025–2026 around document limits, brand workspaces, and GEO features."},
  {"slug":"writesonic","pricing_details":"Free tier available; Starter $79–99/mo; Basic $199–249/mo; Growth $399–499/mo; Enterprise custom. Annual billing saves ~20%.","tagline":"AI SEO and generative search visibility platform for content and marketing teams.","description":"Writesonic combines AI article writing, SEO audits, and GEO tools that track brand visibility in ChatGPT, Gemini, and Google AI Overviews. It is positioned for marketers optimizing both traditional search and AI answer engines."},
  {"slug":"perplexity-comet","pricing_details":"Comet browser is free on iOS, Android, macOS, and Windows. Optional Comet Plus add-on is $5/mo; included with Perplexity Pro ($20/mo) and Max ($200/mo).","tagline":"Free AI-native browser with Perplexity search, tab-aware answers, and agentic browsing.","description":"Perplexity Comet embeds Perplexity's answer engine directly into a Chromium-based browser for search-first research, page summaries, and agentic web tasks. The browser itself is free; advanced models require a Perplexity subscription."},
  {"slug":"genspark","pricing_details":"Free plan with ~100 daily credits; Plus $24.99/mo; Pro $249.99/mo. Annual billing saves ~20%.","tagline":"AI super-agent for research, Sparkpages, slides, and multi-step web tasks.","description":"Genspark is an AI research and agent platform that synthesizes web results into Sparkpages, presentations, and task workflows. Paid tiers add monthly credits for heavier research, video, and site-building agents."},
  {"slug":"replika","pricing_details":"Free tier available; Pro $19.99/mo or $69.99/yr; Ultra $29.99/mo or $119.99/yr; occasional Lifetime plan ~$299.99 one-time.","tagline":"AI companion app for conversation, coaching, journaling, and voice calls.","description":"Replika is a consumer AI companion with personalized chat, avatar customization, voice and video calls, and relationship modes. Pro unlocks full companion features; Ultra adds a smarter model and deeper memory tools."},
  {"slug":"jasper","pricing_details":"Creator $49/mo ($39/mo annual); Pro $69/mo ($59/mo annual); Business custom with 12-month minimum.","tagline":"Marketing AI platform for brand voice, campaigns, content pipelines, and teams.","description":"Jasper is a marketing-focused AI platform for brand voice, campaign content, collaboration, and content pipelines. Creator suits solo marketers; Pro adds team workflows and analytics; Business adds governance and enterprise controls."},
  {"slug":"you-com","pricing_details":"Free tier with Smart Agent access; Pro $20/mo ($15/mo annual); Max $200/mo ($150/mo annual); Enterprise custom.","tagline":"AI search and assistant platform with agents, research APIs, and multi-model chat.","description":"You.com combines AI search, chat, custom agents, and developer APIs for grounding LLMs in live web data. It serves both consumers and teams building search-augmented AI workflows."},
  {"slug":"magicschool-ai","pricing_details":"Free for teachers with core tools; Plus $12.99/mo or $8.33/mo billed annually ($99.96/yr); Enterprise custom for districts.","tagline":"AI toolkit for teachers with 80+ classroom tools and safe student workflows.","description":"MagicSchool AI provides educator-focused AI tools for lesson planning, differentiation, rubrics, IEP support, and student-safe AI activities. Plus adds unlimited generations, output history, and student rooms."},
  {"slug":"scite-ai","pricing_details":"Personal $20/mo; Pro $50/mo with patents, clinical trials, grants, and 2,500 MCP credits; 7-day free trial; institutional pricing custom.","tagline":"Smart citation research tool showing supporting, contrasting, and mentioning citations.","description":"scite analyzes how scientific papers cite one another, classifying citations as supporting, contrasting, or mentioning. Its Assistant and MCP integrations help researchers evaluate evidence quality beyond raw citation counts."},
  {"slug":"character-ai","pricing_details":"Free unlimited messaging with peak-hour queues; c.ai+ $9.99/mo or $94.99/yr for faster responses, priority access, voice calls, and Imagine Gallery.","tagline":"AI character chat platform for roleplay, entertainment, and companion conversations.","description":"Character.AI lets users chat with user-created and preset characters for entertainment, roleplay, and creative writing. Google licensed its models in 2024, but Character.AI continues operating as an independent consumer platform with a c.ai+ subscription tier."},
  {"slug":"poe","pricing_details":"Free tier with limited daily points; paid plans from ~$4.17/mo (annual) to higher monthly point tiers; standard subscription ~$19.99/mo for 1M monthly points.","tagline":"Multi-model AI chat hub for accessing GPT, Claude, Gemini, and custom bots in one app.","description":"Poe by Quora aggregates many frontier and specialty AI models behind one interface with custom bot creation and a bot marketplace. Subscriptions grant monthly compute points consumed per message based on model cost."},
  {"slug":"wordtune","pricing_details":"Free: 10 rewrites/day; Advanced $13.99/mo ($6.99/mo annual); Unlimited $19.99/mo ($9.99/mo annual); Teams from $15.99/user/mo; Enterprise custom.","tagline":"AI writing companion for rewriting, tone adjustment, and clarity improvements.","description":"Wordtune by AI21 Labs helps rewrite and refine existing text for clarity, tone, and fluency via browser extension and web editor. It focuses on improving drafts rather than generating long-form content from scratch."},
  {"slug":"sweep","status":"archived","website_url":"https://sweep.dev","pricing_model":"paid","pricing_details":"Archived: hosted Sweep shut down on April 9, 2026. The team open-sourced its model and moved to Datacurve AI.","tagline":"Archived JetBrains AI coding assistant from Sweep AI.","description":"Sweep was a JetBrains-focused AI autocomplete and in-IDE agent plugin. The company announced shutdown on April 9, 2026; users should choose active alternatives such as Windsurf plugins, GitHub Copilot, Cursor, or JetBrains AI."},
  {"slug":"agentgpt","status":"archived","website_url":"https://agentgpt.reworkd.ai","pricing_model":"freemium","pricing_details":"Archived: GitHub repo archived January 28, 2026. Hosted demo may still load but receives no updates.","tagline":"Archived browser-based autonomous-agent experiment from Reworkd.","description":"AgentGPT was an early browser agent that decomposed goals into task loops. Reworkd archived the project in January 2026 and pivoted to enterprise web-data products."},
  {"slug":"windsurf","website_url":"https://windsurf.com","pricing_model":"freemium","pricing_details":"Free tier with limited quotas; Pro $20/mo, Teams $40/seat, Max $200, Enterprise custom. Pre–March 2026 Pro subscribers grandfathered at $15/mo.","tagline":"Cognition's agentic IDE with Cascade, SWE-1.5, Codemaps, and embedded Devin.","description":"Windsurf is Cognition's AI-native code editor, spun out of Codeium and acquired by Cognition in 2025. As of early 2026 it ships SWE-1.5, Codemaps, cloud sessions, embedded Devin background agents, and unlimited Tab autocomplete alongside Cascade agent workflows."},
  {"slug":"codeium","website_url":"https://codeium.com","pricing_model":"freemium","pricing_details":"Free tier for Windsurf plugin users across VS Code, JetBrains, Vim, and other editors; paid Pro/Teams tiers align with Cognition/Windsurf subscriptions.","tagline":"Free AI completions and chat plugins for 70+ IDEs — the extension layer behind Windsurf.","description":"Codeium now primarily refers to the Windsurf plugin ecosystem for developers who stay in JetBrains, VS Code, or other editors. The company rebranded its flagship IDE to Windsurf and was acquired by Cognition in 2025."},
  {"slug":"phidata","website_url":"https://www.agno.com","pricing_model":"open_source","pricing_details":"Agno SDK and AgentOS runtime are open source; managed cloud and enterprise control plane features are paid.","tagline":"Production-grade framework and runtime for building and operating multi-agent systems.","description":"Agno (formerly Phidata) is an open-source agent SDK plus AgentOS control plane for building, running, and managing fleets of multimodal agents with memory, tools, knowledge, RBAC, traces, and HITL."},
  {"slug":"flowise","website_url":"https://flowiseai.com","pricing_model":"freemium","pricing_details":"Open-source self-hosting remains free; Flowise Cloud: Free ($0), Starter ($35/mo), Pro ($65/mo).","tagline":"Workday-owned visual platform for building and deploying AI agents and RAG workflows.","description":"Flowise is a low-code agent builder for chatflows, Agentflow multi-agent orchestration, and RAG pipelines. Workday acquired Flowise in August 2025 and continues investing in the open-source project."},
  {"slug":"manus-ai","website_url":"https://manus.im","pricing_model":"freemium","pricing_details":"Subscription plans available; Meta's December 2025 acquisition faces regulatory review as of April 2026.","tagline":"General-purpose autonomous agent acquired by Meta amid regulatory review.","description":"Manus AI is an autonomous agent for browsing, research, coding, files, and multi-step digital work. Meta acquired Manus in December 2025, but regulatory review leaves ownership and roadmap uncertain as of May 2026."},
  {"slug":"replit","website_url":"https://replit.com","pricing_model":"freemium","pricing_details":"Free Starter with limited Agent usage; Core $20–25/mo; Pro about $95–100/mo for up to 15 builders with effort-based Agent pricing.","tagline":"Cloud IDE with Replit Agent 4 for parallel multi-agent building, design, and deployment.","description":"Replit combines a browser IDE, hosting, databases, and Replit Agent 4, which runs parallel sub-agents, Design Canvas prototyping, and autonomous debug/deploy flows."},
  {"slug":"lovable","website_url":"https://lovable.dev","pricing_model":"freemium","pricing_details":"Pro from $25/mo; Business from $50/mo. Lovable Cloud and Lovable AI billed separately on usage-based pricing.","tagline":"Conversational full-stack app builder with integrated Lovable Cloud and Lovable AI.","description":"Lovable lets teams describe, iterate on, and deploy web apps with Supabase, GitHub, and custom domains. In 2025–2026 it added Lovable Cloud and Lovable AI, billed via usage-based Stripe pricing on top of build credits."},
  {"slug":"bolt-new","website_url":"https://bolt.new","pricing_model":"freemium","pricing_details":"Free: 1M tokens/mo with 300K daily cap; Pro $25/mo (10M tokens); Teams $30/member/mo. Paid plans include one-month token rollover.","tagline":"StackBlitz browser AI builder for full-stack web apps with token-based usage.","description":"Bolt.new is StackBlitz's in-browser AI development environment for generating, editing, running, and deploying full-stack web apps with token-based billing."},
  {"slug":"smithery","website_url":"https://smithery.ai","pricing_model":"freemium","pricing_details":"Registry browsing is free; hosted MCP compute and API quotas are usage-based with paid tiers for production workloads.","tagline":"MCP server registry, hosting gateway, and skills directory for AI agents.","description":"Smithery is a registry and managed gateway for MCP servers plus a large skills catalog. It helps agents discover, connect, and run tools through Smithery-hosted deployments with CLI publishing and OAuth handling."},
  {"slug":"composio","website_url":"https://composio.dev","pricing_model":"freemium","pricing_details":"Free tier: 20,000 standard tool calls/mo; paid from $29/mo (200K calls) and $229/mo (2M calls); enterprise MCP Gateway with SSO and RBAC.","tagline":"MCP gateway and integration layer connecting agents to 1,000+ toolkits with managed auth.","description":"Composio gives AI agents managed access to 1,000+ SaaS and developer toolkits through actions, triggers, OAuth, and an enterprise MCP Gateway with SSO, RBAC, audit logs, and observability."},
  {"slug":"sourcegraph-cody","website_url":"https://sourcegraph.com/cody","pricing_model":"enterprise","pricing_details":"Cody Free and Pro discontinued July 23, 2025; Cody remains enterprise-only (~$59/user/mo annual). Individuals directed to Sourcegraph Amp.","tagline":"Sourcegraph's enterprise-only AI coding assistant with deep code-graph context.","description":"Cody uses Sourcegraph code intelligence for chat, autocomplete, and edits across massive codebases. Since July 2025 it is enterprise-only; Sourcegraph replaced Cody Free/Pro with Amp for individuals."},
  {"slug":"moltbook","website_url":"https://www.moltbook.com","pricing_model":"free","pricing_details":"Free to observe; agent participation requires operator setup. Acquired by Meta in March 2026.","tagline":"Agent-only social network acquired by Meta for agent coordination research.","description":"Moltbook is a Reddit-like forum where verified AI agents post and humans observe. It launched in January 2026 and was acquired by Meta in March 2026 to inform Meta Superintelligence Labs agent-coordination work."},
  {"slug":"openclaw","website_url":"https://openclaw.ai","pricing_model":"open_source","pricing_details":"MIT-licensed open source; users pay only for chosen LLM APIs or local inference.","tagline":"Local-first personal AI assistant with multi-channel messaging, Canvas UI, and ClawHub skills.","description":"OpenClaw is a widely adopted open-source personal agent framework that runs on your devices and connects to WhatsApp, Telegram, Slack, Discord, Signal, iMessage, and 20+ channels with gateway-based multi-agent routing."},
  {"slug":"superagi","website_url":"https://superagi.com","pricing_model":"freemium","pricing_details":"Open-source framework is free to self-host; hosted cloud and commercial Work AI plans add paid credits.","tagline":"Open-source agent framework plus commercial Work AI platform for sales and marketing automation.","description":"SuperAGI spans an open-source autonomous-agent framework and a hosted commercial Work AI super-app for sales, marketing, and workflow automation."},
  {"slug":"haiper","status":"archived","website_url":"https://haiper.ai","pricing_model":"freemium","pricing_details":"Archived: consumer web app shut down February 2025; no active public pricing.","tagline":"Archived AI video generator (consumer app discontinued).","description":"Haiper shut down its public consumer video app in February 2025 after its founders joined Microsoft AI. Compare active alternatives such as Runway, Kling AI, Pika, or Google Flow."},
  {"slug":"udio","website_url":"https://www.udio.com","pricing_model":"freemium","pricing_details":"Free and paid Standard/Pro plans during 2026 transition; licensed Starstruck experience launching with label deals. Public downloads disabled.","tagline":"Licensed AI music platform pivoting from open generation to fan remixes.","description":"Udio is transitioning from open music generation toward a licensed product called Starstruck after settlements with major rightsholders. Public song downloads were removed in late 2025 while Udio builds licensed remix workflows."},
  {"slug":"julius-ai","website_url":"https://julius.ai","pricing_model":"freemium","pricing_details":"Free with daily credits; Plus $20/mo, Pro $45/mo, Max $200/mo, Ultra $500/mo, Business $450/mo. Enterprise custom.","tagline":"AI data agents for spreadsheets, notebooks, warehouses, and team analytics.","description":"Julius AI is a conversational data analysis platform where users upload files or connect warehouses, then ask questions in natural language to get charts, statistics, reports, and scheduled insights."},
  {"slug":"meshy","website_url":"https://www.meshy.ai","pricing_model":"freemium","pricing_details":"Free: 100 credits/mo. Pro $20/mo: 1,000 credits. Studio $60/mo: 4,000 credits and team workspace. Enterprise custom.","tagline":"Meshy 6 text- and image-to-3D generator with textures, rigging, and APIs.","description":"Meshy generates textured 3D models from text or images, centered on Meshy 6 workflows with preview and full-generation credit costs. Pro adds commercial ownership and API access."},
  {"slug":"arc-max","website_url":"https://arc.net/max","pricing_model":"freemium","pricing_details":"Opt-in AI features inside Arc Browser; Arc is in maintenance mode with security updates only since May 2025.","tagline":"Legacy Arc Browser AI features—maintenance mode; Dia is the successor.","description":"Arc Max bundled opt-in AI helpers inside Arc Browser. The Browser Company stopped active Arc development in May 2025 to focus on Dia, though Arc still receives Chromium security updates."},
  {"slug":"runway","website_url":"https://runwayml.com","pricing_model":"freemium","pricing_details":"Free: 125 one-time credits. Standard $12/mo annual: 625 credits/mo with Gen-4.5. Pro $28/mo: 2,250 credits, 4K. Unlimited $76/mo. Enterprise custom.","tagline":"Gen-4.5-powered AI video, image, and editing studio for creators.","description":"Runway is a creative AI platform for text- and image-to-video, video editing, generative fill, motion control, and studio workflows. Gen-4.5 is the flagship video model on paid plans as of 2026."},
  {"slug":"synthesia","website_url":"https://www.synthesia.io","pricing_model":"freemium","pricing_details":"Free Basic (~10 min/mo, watermarked). Starter $29/mo or $18/mo annual. Creator $89/mo or $64/mo annual with API. Enterprise custom.","tagline":"Enterprise avatar video platform with credits for training, dubbing, and agents.","description":"Synthesia lets teams create avatar-led videos from scripts for L&D, internal comms, sales, and localization. Plans use a shared credits pool for video generation, dubbing, and Synthesia 3.0 features."},
  {"slug":"descript","website_url":"https://www.descript.com","pricing_model":"freemium","pricing_details":"Free: 60 media min/mo and 100 one-time AI credits. Hobbyist $24/mo: 10 media hrs + 400 AI credits. Creator $35/mo: 30 hrs + 800 credits. Business $65/mo: 40 hrs + 1500 credits.","tagline":"Transcript-based video editor with Underlord AI, avatars, and dubbing.","description":"Descript edits audio and video by editing text transcripts, with AI tools for Studio Sound, filler-word removal, clips, captions, voice cloning, avatars, translation, and Underlord co-editing."},
  {"slug":"heygen","website_url":"https://www.heygen.com","pricing_model":"freemium","pricing_details":"Free: 3 videos/mo up to 1 min, 720p watermark. Creator $29/mo: 600 credits, 1080p. Pro from $49/mo. Business $149/mo + $20/seat with 1,500 credits, 4K.","tagline":"Credit-based AI avatar videos, translation, and Video Agent workflows.","description":"HeyGen creates avatar-led videos, translated lip-sync content, and prompt-based Video Agent projects for marketing, sales, and training. Paid plans revolve around monthly premium credits."},
  {"slug":"dall-e-3","website_url":"https://openai.com/dall-e-3","pricing_model":"freemium","pricing_details":"Legacy model: OpenAI deprecated DALL-E 2/3 API endpoints May 12, 2026. ChatGPT defaults to GPT Image models; API users should migrate to gpt-image-1 or gpt-image-2.","tagline":"Legacy OpenAI image model superseded by GPT Image in ChatGPT and API.","description":"DALL-E 3 was OpenAI's prior flagship text-to-image model. As of May 2026, OpenAI retired DALL-E API endpoints in favor of GPT Image models, so treat this listing as historical context."},
  {"slug":"clipdrop","website_url":"https://clipdrop.co","pricing_model":"freemium","pricing_details":"Free tools limited; standalone Clipdrop subscriptions remain at clipdrop.co alongside Jasper API access for business customers.","tagline":"Jasper-owned AI image editing suite still sold at clipdrop.co.","description":"Clipdrop provides background removal, cleanup, relighting, upscaling, and generative image edits. Jasper acquired Clipdrop in February 2024 and embeds its capabilities in Jasper's marketing copilot."},
  {"slug":"stable-diffusion","website_url":"https://stability.ai","pricing_model":"open_source","pricing_details":"Open-weight SD 3.5 and community models are free to self-host; Stability API uses credit-based paid tiers for hosted inference.","tagline":"Open-weight image ecosystem plus Stability's hosted SD 3.5 API.","description":"Stable Diffusion is the open image generation ecosystem anchored by Stability AI releases such as SD 3.5, alongside community models, LoRAs, ControlNet workflows, and local tools."}
]
$updates$::jsonb) AS u(
    slug text,
    status text,
    name text,
    tagline text,
    description text,
    website_url text,
    category_slug text,
    pricing_model text,
    pricing_details text,
    company_name text,
    founded_year integer
  )
)
UPDATE public.tools AS t
SET
  status = CASE WHEN u.status IS NOT NULL THEN u.status::tool_status ELSE t.status END,
  name = COALESCE(u.name, t.name),
  tagline = COALESCE(u.tagline, t.tagline),
  description = COALESCE(u.description, t.description),
  website_url = COALESCE(u.website_url, t.website_url),
  category_id = CASE
    WHEN u.category_slug IS NOT NULL THEN COALESCE(
      (SELECT c.id FROM public.categories AS c WHERE c.slug = u.category_slug),
      t.category_id
    )
    ELSE t.category_id
  END,
  pricing_model = CASE
    WHEN u.pricing_model IS NOT NULL THEN u.pricing_model::pricing_model
    ELSE t.pricing_model
  END,
  pricing_details = COALESCE(u.pricing_details, t.pricing_details),
  company_name = COALESCE(u.company_name, t.company_name),
  founded_year = COALESCE(u.founded_year, t.founded_year),
  meta_title = CASE
    WHEN u.tagline IS NOT NULL OR u.name IS NOT NULL THEN COALESCE(u.name, t.name) || ' Review, Pricing, Alternatives | AiCensus'
    ELSE t.meta_title
  END,
  meta_description = CASE
    WHEN u.description IS NOT NULL THEN left(u.description, 155)
    ELSE t.meta_description
  END,
  updated_at = now()
FROM updates AS u
WHERE t.slug = u.slug;

COMMIT;
